import type {Note,StudySet} from "./schemas";
export const sampleStudy:StudySet={
 flashcards:[
  {question:"Phân số biểu diễn điều gì?",answer:"Một phần của đơn vị được chia thành các phần bằng nhau."},
  {question:"Cộng hai phân số cùng mẫu số như thế nào?",answer:"Cộng tử số và giữ nguyên mẫu số."},
  {question:"3/4 + 1/4 bằng bao nhiêu?",answer:"4/4 = 1."},
  {question:"Cộng hai phân số khác mẫu cần làm gì trước?",answer:"Quy đồng mẫu số, rồi cộng các tử số."},
  {question:"1/2 + 1/3 bằng bao nhiêu?",answer:"3/6 + 2/6 = 5/6."},
  {question:"Tính xong một phân số cần kiểm tra điều gì?",answer:"Rút gọn kết quả nếu có thể; mẫu số phải khác 0."}],
 quiz:[
  {question:"3/4 + 1/4 bằng bao nhiêu?",options:["1/2","1","3/8","2"],answer:1,explanation:"Cùng mẫu 4 nên cộng tử: (3 + 1)/4 = 4/4 = 1."},
  {question:"1/2 + 1/3 bằng bao nhiêu?",options:["2/5","1/6","5/6","2/6"],answer:2,explanation:"Quy đồng mẫu 6: 1/2 = 3/6, 1/3 = 2/6. Tổng là 5/6."},
  {question:"Khi cộng hai phân số khác mẫu, em làm gì trước?",options:["Cộng mẫu số","Nhân tử số","Bỏ mẫu số","Quy đồng mẫu số"],answer:3,explanation:"Cần đưa hai phân số về cùng mẫu trước khi cộng tử số."},
  {question:"Rút gọn 4/6 được phân số nào?",options:["2/3","1/3","4/3","2/6"],answer:0,explanation:"Chia cả tử và mẫu cho 2: 4/6 = 2/3."},
  {question:"Mẫu số của một phân số phải thỏa điều kiện nào?",options:["Luôn là 1","Khác 0","Luôn âm","Bằng tử số"],answer:1,explanation:"Không thể chia cho 0, nên mẫu số phải khác 0."}],
 pairs:[{term:"Tử số",definition:"Số nằm phía trên gạch phân số"},{term:"Mẫu số",definition:"Số nằm phía dưới, phải khác 0"},{term:"Quy đồng",definition:"Đưa các phân số về cùng mẫu"},{term:"Rút gọn",definition:"Chia tử và mẫu cho cùng ước chung khác 0"},{term:"Phân số bằng nhau",definition:"Biểu diễn cùng một giá trị"}]
};
const base={images:[],createdAt:"2026-10-01T08:00:00.000Z"};
export const demoNotes:Note[]=[
 {...base,id:"11111111-1111-4111-8111-111111111111",grade:6,title:"Cộng và rút gọn phân số",subject:"Toán học",chapter:"Chương 5 · Phân số",summary:"Cộng cùng mẫu, quy đồng khác mẫu và rút gọn kết quả. Từng bước nhỏ để hiểu chắc phân số.",tags:["Phân số","Quy đồng","Lớp 6"],study:sampleStudy,updatedAt:"2026-10-05T06:00:00.000Z",content:"# Cộng và rút gọn phân số\n\n## Phân số là gì?\nPhân số $\\frac{a}{b}$ có tử số $a$ và mẫu số $b$, với $b\\ne0$. Phân số có thể biểu diễn một phần của đơn vị đã chia thành các phần bằng nhau.\n\n## Cộng cùng mẫu\nCộng các tử số và giữ nguyên mẫu số:\n$$\\frac{a}{m}+\\frac{b}{m}=\\frac{a+b}{m}$$\nVí dụ: $\\frac34+\\frac14=\\frac44=1$.\n\n## Cộng khác mẫu\nQuy đồng mẫu số trước, rồi cộng tử số.\n$$\\frac12+\\frac13=\\frac36+\\frac26=\\frac56$$\n\n## Rút gọn\nChia tử và mẫu cho cùng một ước chung khác 0. Ví dụ: $\\frac46=\\frac23$.\n\n> Đừng cộng hai mẫu số! Sau khi tính, hãy kiểm tra có thể rút gọn không."},
 {...base,id:"22222222-2222-4222-8222-222222222222",grade:7,title:"Tốc độ và chuyển động",subject:"Khoa học tự nhiên",chapter:"Chủ đề · Tốc độ",summary:"Quãng đường, thời gian, tốc độ và cách đổi đơn vị trước khi tính.",tags:["Tốc độ","Chuyển động","Lớp 7"],updatedAt:"2026-10-04T06:00:00.000Z",content:"# Tốc độ và chuyển động\n\nTốc độ cho biết mức độ nhanh hay chậm của chuyển động.\n\n## Công thức\n$$v=\\frac{s}{t}$$\nTrong đó $v$ là tốc độ, $s$ là quãng đường và $t$ là thời gian.\n\n## Đơn vị\nCó thể dùng m/s hoặc km/h. $1\\text{ m/s}=3.6\\text{ km/h}$. Đổi đơn vị thống nhất trước khi tính.\n\n## Ví dụ\nMột bạn đi 120 m trong 60 s, tốc độ là $120/60=2$ m/s.\n\n> Công thức trên cho tốc độ trung bình trên quãng đường đang xét."},
 {...base,id:"33333333-3333-4333-8333-333333333333",grade:6,title:"Đọc hiểu truyện đồng thoại",subject:"Ngữ văn",chapter:"Chủ đề · Truyện đồng thoại",summary:"Nhân vật, ngôi kể, chi tiết và bài học được gợi ra từ truyện đồng thoại.",tags:["Đọc hiểu","Nhân vật","Lớp 6"],updatedAt:"2026-10-03T06:00:00.000Z",content:"# Đọc hiểu truyện đồng thoại\n\nTruyện đồng thoại thường có nhân vật là loài vật hoặc đồ vật được nhân cách hóa. Nhân vật vừa giữ đặc điểm vốn có, vừa có suy nghĩ, cảm xúc hay hành động như con người.\n\n## Đọc theo từng bước\n1. Xác định nhân vật và sự việc chính.\n2. Tìm ngôi kể: người kể xưng tôi hay kể về nhân vật?\n3. Chọn chi tiết thể hiện tính cách và sự thay đổi của nhân vật.\n4. Nêu bài học, dựa trên chi tiết trong văn bản.\n\n> Khi phân tích, cần dẫn chi tiết từ truyện cụ thể. Không tự tạo trích dẫn."},
 {...base,id:"44444444-4444-4444-8444-444444444444",grade:7,title:"Present Simple & Present Continuous",subject:"Tiếng Anh",chapter:"Chủ đề · Everyday activities",summary:"Phân biệt thói quen với hành động đang diễn ra; cấu trúc và từ chỉ thời gian.",tags:["Grammar","Tenses","Lớp 7"],updatedAt:"2026-10-02T06:00:00.000Z",content:"# Present Simple & Present Continuous\n\n## Present Simple\nDiễn tả thói quen hoặc sự thật. S + V; với he/she/it thường thêm -s/-es.\n\nI walk to school every day. She plays badminton on Sundays.\n\n## Present Continuous\nDiễn tả hành động đang diễn ra: S + am/is/are + V-ing.\n\nI am reading now. They are playing outside.\n\n## So sánh\nEvery day, usually, often thường gắn với thói quen; now, at the moment thường gắn với hành động hiện tại. Cần đọc cả ngữ cảnh, không chỉ một từ khóa."},
 {...base,id:"55555555-5555-4555-8555-555555555555",grade:8,title:"Hằng đẳng thức bình phương một tổng",subject:"Toán học",chapter:"Chủ đề · Hằng đẳng thức",summary:"Hiểu (a+b)² = a² + 2ab + b² qua phép nhân và một ví dụ cụ thể.",tags:["Đại số","Hằng đẳng thức","Lớp 8"],updatedAt:"2026-10-01T06:00:00.000Z",content:"# Bình phương một tổng\n\n$$ (a+b)^2=a^2+2ab+b^2 $$\n\n## Vì sao?\n$(a+b)(a+b)=a^2+ab+ab+b^2=a^2+2ab+b^2$.\n\n## Ví dụ\n$(x+3)^2=x^2+6x+9$.\n\n> Lỗi thường gặp: quên số hạng 2ab. Bình phương một tổng không chỉ là tổng hai bình phương."},
 {...base,id:"66666666-6666-4666-8666-666666666666",grade:9,title:"Căn bậc hai và căn thức",subject:"Toán học",chapter:"Chủ đề · Căn bậc hai",summary:"Căn bậc hai số học và điều kiện xác định của căn thức.",tags:["Căn thức","Điều kiện","Lớp 9"],updatedAt:"2026-09-30T06:00:00.000Z",content:"# Căn bậc hai và căn thức\n\nVới $a\\ge0$, căn bậc hai số học $\\sqrt a$ là số không âm có bình phương bằng $a$.\n\nVí dụ: $\\sqrt{25}=5$. Phương trình $x^2=25$ có hai nghiệm $x=5$ hoặc $x=-5$, nhưng căn bậc hai số học của 25 là 5.\n\n## Điều kiện xác định\n$\\sqrt{A}$ xác định khi $A\\ge0$. Với $\\sqrt{x-2}$, điều kiện là $x\\ge2$.\n\n> Phân biệt căn bậc hai số học với hai nghiệm của phương trình bình phương."}
];
export function cloneDemo(){return structuredClone(demoNotes);}
