import type {Note,StudySet} from "./schemas";
export const sampleStudy:StudySet={
flashcards:[
{question:"Phân phối nhị thức mô tả điều gì?",answer:"Số lần thành công trong n phép thử độc lập, cùng xác suất thành công p."},
{question:"Công thức xác suất P(X=k)?",answer:"P(X=k) = C(n,k) · pᵏ · (1−p)ⁿ⁻ᵏ."},
{question:"Kỳ vọng của X ~ Bin(n,p)?",answer:"E(X) = n · p."},
{question:"Phương sai của X ~ Bin(n,p)?",answer:"Var(X) = n · p · (1−p)."},
{question:"Tung đồng xu công bằng 10 lần. Kỳ vọng số mặt ngửa?",answer:"E(X) = 10 × 0,5 = 5."},
{question:"Các phép thử nhị thức có cần độc lập?",answer:"Có. Mỗi phép thử độc lập và p không đổi."}],
quiz:[
{question:"X ~ Bin(10; 0,5). E(X) bằng bao nhiêu?",options:["2,5","5","10","0,5"],answer:1,explanation:"E(X) = np = 10 × 0,5 = 5."},
{question:"X ~ Bin(10; 0,5). Phương sai bằng bao nhiêu?",options:["5","10","2,5","0,25"],answer:2,explanation:"Var(X) = np(1−p) = 10 × 0,5 × 0,5 = 2,5."},
{question:"Điều kiện nào bắt buộc trong mô hình nhị thức?",options:["Phép thử phụ thuộc","p thay đổi","Số phép thử vô hạn","Các phép thử độc lập"],answer:3,explanation:"Mô hình yêu cầu n cố định, hai kết quả, độc lập, p không đổi."},
{question:"Nếu p = 1, X nhận giá trị nào?",options:["n","0","n/2","Không xác định"],answer:0,explanation:"Mọi phép thử thành công nên X = n."},
{question:"C(n,k) trong công thức xác suất là gì?",options:["Số hoán vị","Số cách chọn k trong n phần tử","Kỳ vọng","Xác suất thành công"],answer:1,explanation:"Đếm cách chọn k vị trí thành công trong n phép thử."}],
pairs:[{term:"n",definition:"Số phép thử cố định"},{term:"p",definition:"Xác suất thành công mỗi phép thử"},{term:"np",definition:"Kỳ vọng số thành công"},{term:"np(1−p)",definition:"Phương sai số thành công"},{term:"C(n,k)",definition:"Số cách chọn k vị trí trong n"}]};
const base={images:[],createdAt:"2026-10-01T08:00:00.000Z"};
export const demoNotes:Note[]=[
{...base,id:"11111111-1111-4111-8111-111111111111",title:"Phân phối nhị thức",subject:"Xác suất thống kê",chapter:"Chương 3 · Biến ngẫu nhiên",summary:"Từ phép thử Bernoulli đến xác suất, kỳ vọng và phương sai.",tags:["Nhị thức","Kỳ vọng","Bernoulli"],study:sampleStudy,updatedAt:"2026-10-05T06:00:00.000Z",
content:"# Phân phối nhị thức\n\n## 1. Từ phép thử đến phân phối\nPhép thử Bernoulli có hai kết quả: thành công hoặc thất bại. Với $n$ phép thử độc lập, xác suất thành công $p$ không đổi, số lần thành công $X \\sim \\mathrm{Bin}(n,p)$.\n\n## 2. Công thức xác suất\n$$P(X=k)=\\binom{n}{k}p^k(1-p)^{n-k}$$\nVới $k=0,1,\\ldots,n$. $\\binom{n}{k}$ là số cách chọn $k$ vị trí thành công trong $n$ phép thử.\n\n## 3. Kỳ vọng và phương sai\n- $E(X)=np$.\n- $\\mathrm{Var}(X)=np(1-p)$.\n\n## 4. Ví dụ\nTung đồng xu công bằng 10 lần: $n=10$, $p=0.5$. Kỳ vọng số mặt ngửa là 5, phương sai 2.5. Nếu $p=1$, mọi phép thử thành công và $X=n$.\n\n> Điều kiện: n cố định, hai kết quả, độc lập, p không đổi."},
{...base,id:"22222222-2222-4222-8222-222222222222",title:"Quy trình Data Science",subject:"Khoa học dữ liệu",chapter:"Chương 1 · Nhập môn",summary:"Hiểu vấn đề, chuẩn bị dữ liệu, mô hình hóa, đánh giá, triển khai và phản hồi.",tags:["Data Science","Pipeline"],updatedAt:"2026-10-04T06:00:00.000Z",content:"# Quy trình khoa học dữ liệu\n\n## Hiểu vấn đề\nXác định câu hỏi kinh doanh và tiêu chí thành công.\n\n## Thu thập và chuẩn bị\nThu thập dữ liệu phù hợp; xử lý giá trị thiếu, trùng lặp và lỗi định dạng.\n\n## Mô hình hóa\nChia train, validation và test. Chọn mô hình theo validation; dùng test để đánh giá cuối.\n\n## Triển khai và phản hồi\nTheo dõi chất lượng và cập nhật khi dữ liệu thay đổi."},
{...base,id:"33333333-3333-4333-8333-333333333333",title:"Định luật Newton",subject:"Vật lý",chapter:"Chương 2 · Động lực học",summary:"Ba định luật Newton và quan hệ lực, khối lượng, gia tốc.",tags:["Cơ học","Lực"],updatedAt:"2026-10-03T06:00:00.000Z",content:"# Ba định luật Newton\n\n1. Quán tính: vật giữ trạng thái đứng yên hoặc chuyển động thẳng đều khi hợp lực bằng không.\n2. Động lực học: $\\vec F=m\\vec a$.\n3. Tương tác: hai lực cùng độ lớn, ngược chiều và đặt lên hai vật khác nhau.\n\nVí dụ: hợp lực 10 N tác dụng lên vật 2 kg tạo gia tốc 5 m/s²."},
{...base,id:"44444444-4444-4444-8444-444444444444",title:"Present Perfect",subject:"Tiếng Anh",chapter:"Unit 4 · Tenses",summary:"Have/has + V3; since, for, already và yet.",tags:["Grammar","Tenses"],updatedAt:"2026-10-02T06:00:00.000Z",content:"# Present Perfect\n\nS + have/has + past participle (V3).\n\nDùng cho trải nghiệm; hành động quá khứ liên quan hiện tại; hành động bắt đầu quá khứ và còn tiếp tục.\n\n- Since: mốc thời gian, since 2020.\n- For: khoảng thời gian, for two years.\n- Already: đã.\n- Yet: chưa/đã chưa, thường trong phủ định và câu hỏi.\n\nI have studied English for two years."},
{...base,id:"55555555-5555-4555-8555-555555555555",title:"Phân phối đều liên tục",subject:"Xác suất thống kê",chapter:"Chương 3 · Biến ngẫu nhiên",summary:"Mật độ không đổi trên [a,b], kỳ vọng và phương sai.",tags:["Uniform","Liên tục"],updatedAt:"2026-10-01T06:00:00.000Z",content:"# Phân phối đều liên tục\n\n$X \\sim U(a,b)$ có mật độ $f(x)=1/(b-a)$ trên $[a,b]$, bằng 0 ở ngoài.\n\n- $E(X)=(a+b)/2$.\n- $\\mathrm{Var}(X)=(b-a)^2/12$.\n- $P(c\\le X\\le d)=(d-c)/(b-a)$ nếu $a\\le c<d\\le b$.\n\nVí dụ U(0,10): xác suất nằm từ 2 đến 5 bằng 3/10."},
{...base,id:"66666666-6666-4666-8666-666666666666",title:"SQL: JOIN và GROUP BY",subject:"Khoa học dữ liệu",chapter:"Chương 3 · Cơ sở dữ liệu",summary:"Kết hợp bảng theo khóa và tổng hợp dữ liệu theo nhóm.",tags:["SQL","Database"],updatedAt:"2026-09-30T06:00:00.000Z",content:"# JOIN và GROUP BY\n\nINNER JOIN giữ hàng khớp cả hai bảng. LEFT JOIN giữ tất cả hàng bảng trái; bên phải không khớp là NULL.\n\nGROUP BY gom các hàng cùng giá trị. COUNT, SUM, AVG tính thống kê theo nhóm. WHERE lọc trước khi nhóm, HAVING lọc sau tổng hợp.\n\n    SELECT subject, COUNT(*) AS total\n    FROM notes\n    GROUP BY subject\n    HAVING COUNT(*) > 1;"}
];
export function cloneDemo(){return structuredClone(demoNotes);}
