import {test,expect} from "@playwright/test";import {build} from "esbuild";import path from "node:path";import {readFile} from "node:fs/promises";
let fixture:string;
const extraction={title:"Cùng hiểu phân số",subject:"Toán học",chapter:"Phân số",content:"## Khái niệm\n\nPhân số biểu thị một phần của đơn vị.\n\n## Ví dụ trong bản ghi\n\n- Một phần hai.",summary:"Phân số và ví dụ.",tags:["Phân số"],uncertain:[]};
test.beforeAll(async()=>{const root=path.resolve(__dirname,"../..");const result=await build({entryPoints:[path.join(root,"tests/fixtures/voice-page.tsx")],bundle:true,write:false,jsx:"automatic",platform:"browser",minify:true,define:{"process.env.NODE_ENV":"\"production\"","process.env":"{}"},plugins:[{name:"voice-service-boundaries",setup(b){b.onResolve({filter:/^(@\/lib\/firebase|\.\/firebase|next\/link)$/},args=>({path:args.path,namespace:"voice-mock"}));b.onLoad({filter:/.*/,namespace:"voice-mock"},args=>({contents:args.path!=="next/link"?'const user={uid:"voice-test",getIdToken:async()=>"mock-token"};export const firebaseAuth=()=>({currentUser:user});':"import {createElement} from 'react';export default function Link({href,children,...props}){return createElement('a',{href,...props},children)}",loader:"js",resolveDir:root}));}}]});const css=await readFile(path.join(root,"src/app/globals.css"),"utf8");fixture=`<!doctype html><html lang="vi"><head><style>${css}</style></head><body><div id="root"></div><script>${result.outputFiles[0].text.replace(/<\/script/gi,"<\\/script")}</script></body></html>`;});
test.beforeEach(async({page})=>{await page.route("**/__voice-fixture",r=>r.fulfill({contentType:"text/html",body:fixture}));await page.goto("/__voice-fixture");});
async function upload(page:import('@playwright/test').Page){await page.getByLabel('File âm thanh').setInputFiles({name:'speech.wav',mimeType:'audio/wav',buffer:Buffer.from('RIFF0000WAVEfmt ')});await page.getByRole('checkbox').check();}
test("audio automatically reaches Gemini after VietScribe and opens a formatted preview before save",async({page})=>{
 const paths:string[]=[];await page.route('**/api/transcribe',r=>{paths.push('asr');return r.fulfill({json:{transcript:'Phan so la mot phan cua don vi'}});});await page.route('**/api/voice-draft',r=>{paths.push('gemini');const b=r.request().postDataBuffer()!.toString();expect(b).toContain('consentGemini');expect(b).toContain('Phan so la mot phan cua don vi');expect(b).toContain('speech.wav');return r.fulfill({json:{extraction}});});
 await upload(page);await page.getByRole('button',{name:'Nhận dạng & tạo bản ghi'}).click();await expect(page.getByRole('heading',{name:'Khái niệm',exact:true})).toBeVisible();expect(paths).toEqual(['asr','gemini']);await expect(page.getByLabel('Tên bài học')).toHaveValue(extraction.title);await expect(page.getByLabel('Môn học',{exact:true})).toHaveValue('Toán học');await expect(page.getByLabel('Saved note')).toHaveCount(0);await page.getByRole('button',{name:'Lưu vào thư viện'}).click();await expect(page.getByLabel('Saved note')).toContainText('## Khái niệm');
});
test("Gemini reads the original audio when VietScribe quota is exhausted",async({page})=>{
 await page.route('**/api/transcribe',r=>r.fulfill({status:429,json:{error:'ZeroGPU quota',code:'VOICE_QUOTA'}}));await page.route('**/api/voice-draft',r=>{expect(r.request().postDataBuffer()!.toString()).toContain('speech.wav');return r.fulfill({json:{extraction}});});await upload(page);await page.getByRole('button',{name:'Nhận dạng & tạo bản ghi'}).click();await expect(page.getByText('VietScribe chưa sẵn sàng; bản nháp này được Gemini đọc trực tiếp từ âm thanh.')).toBeVisible();await expect(page.getByRole('heading',{name:'Khái niệm',exact:true})).toBeVisible();
});
test("Gemini failure retains the transcript and permits manual save",async({page})=>{
 await page.route('**/api/transcribe',r=>r.fulfill({json:{transcript:'Nội dung bài học cần giữ nguyên để em tự sửa.'}}));await page.route('**/api/voice-draft',r=>r.fulfill({status:502,json:{error:'Gemini đang bận',code:'AI_UPSTREAM'}}));await upload(page);await page.getByRole('button',{name:'Nhận dạng & tạo bản ghi'}).click();await expect(page.getByRole('alert')).toContainText('Gemini đang bận');await expect(page.getByLabel('Nội dung nhận dạng — em có thể sửa lại')).toHaveValue('Nội dung bài học cần giữ nguyên để em tự sửa.');await page.getByRole('button',{name:'Tạo bài từ bản chép lời'}).click();await expect(page.locator('.editor-preview')).toContainText('Nội dung bài học cần giữ nguyên');
});
test("transcript focus uses one boundary and textarea grows without mobile overflow",async({page})=>{await page.setViewportSize({width:320,height:900});const field=page.getByLabel('Nội dung nhận dạng — em có thể sửa lại');await field.fill('Một dòng bài học');await field.focus();expect(await field.evaluate(e=>getComputedStyle(e).outlineStyle)).toBe('none');const h=await field.evaluate(e=>e.clientHeight);await field.fill('Một dòng bài học\n'.repeat(30));expect(await field.evaluate(e=>e.clientHeight)).toBeGreaterThan(h);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
