import Link from "next/link";
import {ArrowRight, Camera, Sparkles, MessageCircle, Gamepad2, BookOpen, Check, Atom, Calculator, Languages, Feather, ChevronRight} from "lucide-react";
import {Logo} from "@/components/ui";
import {AppearanceControls} from "@/components/appearance";
import {LearningScene} from "@/components/learning-scene";

export default function Page(){return <div className="landing">
  <nav className="landing-nav" aria-label="Điều hướng chính"><Logo/><div className="landing-links"><a href="#how">Cách hoạt động</a><a href="#subjects">Môn học</a><a href="#features">Góc khám phá</a></div><div className="nav-actions"><AppearanceControls/><Link href="/login" className="text-button">Đăng nhập</Link><Link href="/register" className="button primary small">Bắt đầu <ArrowRight size={16}/></Link></div></nav>
  <main>
    <section className="landing-hero"><div className="hero-copy"><span className="pill"><span className="live-dot"/> KHÔNG GIAN HỌC TẬP · LỚP 6—9</span><h1>Mỗi trang vở,<br/>một <em>vũ trụ mới.</em><span className="heading-star">✦</span></h1><p>Chụp lại điều em vừa học. Hiểu bài cùng gia sư AI. Chơi một chút, nhớ thêm một chút — tất cả trong không gian của riêng em.</p><div className="hero-actions"><Link className="button primary" href="/register">Mở vũ trụ của em <ArrowRight size={19}/></Link><Link className="button secondary" href="/app?mode=demo">Khám phá bản mẫu <ChevronRight size={18}/></Link></div><div className="hero-proof"><span className="proof-icons"><Calculator size={16}/><Atom size={16}/><Languages size={16}/></span><div><strong>Toán, Văn, Anh, Khoa học…</strong><span>Từ lớp 6 đến lớp 9. Theo nhịp của em.</span></div></div></div><LearningScene/></section>
    <div className="subject-ribbon" aria-hidden="true"><span><Calculator/>TOÁN HỌC</span><i>✦</i><span><Feather/>NGỮ VĂN</span><i>✦</i><span><Atom/>KHOA HỌC TỰ NHIÊN</span><i>✦</i><span><Languages/>TIẾNG ANH</span><i>✦</i><span><BookOpen/>LỊCH SỬ & ĐỊA LÍ</span></div>
    <section id="how" className="how-section"><div className="section-intro"><span className="eyebrow">TỪ TRANG VỞ ĐẾN “À, MÌNH HIỂU RỒI!”</span><h2>Một cách học.<br/><em>Nhiều điều thú vị.</em></h2><p>Giữ những gì em học. Biến chúng thành những gì em hiểu.</p></div><div className="how-grid">{[{n:"01",icon:Camera,title:"Chụp một trang vở",text:"Gemini đọc chữ và công thức. Em kiểm tra, sửa lại rồi lưu bài theo lớp, môn và chương.",color:"teal"},{n:"02",icon:MessageCircle,title:"Gỡ rối cùng gia sư",text:"Mistral tìm bài đã lưu trong thư viện của em, giải thích từng bước và gợi ý để em tự tìm đáp án.",color:"purple"},{n:"03",icon:Gamepad2,title:"Chơi để nhớ lâu",text:"Lật thẻ, thử sức với quiz, ghép những ý tưởng. Mỗi lượt ôn có kết quả và ngày ôn gợi ý.",color:"orange"}].map(s=><article className={s.color} key={s.n}><div><span className="step-icon"><s.icon size={26}/></span><b>{s.n}</b></div><h3>{s.title}</h3><p>{s.text}</p><span className="step-line"/></article>)}</div></section>
    <section id="subjects" className="landing-subjects"><div><span className="eyebrow">KIẾN THỨC Ở ĐÚNG CHỖ</span><h2>Đi từ môn học<br/>đến điều em tò mò.</h2><p>Lớp → môn → chương → bài. Thư viện gọn gàng để em mở lại kiến thức bất cứ lúc nào.</p><Link href="/app?mode=demo&view=library" className="text-button">Ghé thư viện mẫu <ArrowRight size={17}/></Link><div className="grade-pills">{[6,7,8,9].map(g=><span key={g}>Lớp {g}</span>)}</div></div><div className="subject-preview">{[{icon:Calculator,name:"Toán học",text:"Phân số · Hình học · Đại số",color:"purple"},{icon:Atom,name:"Khoa học tự nhiên",text:"Lực · Năng lượng · Sự sống",color:"teal"},{icon:Feather,name:"Ngữ văn",text:"Đọc hiểu · Viết · Cảm nhận",color:"orange"},{icon:Languages,name:"Tiếng Anh",text:"Từ vựng · Ngữ pháp · Giao tiếp",color:"blue"}].map(s=><Link href="/app?mode=demo&view=library" className={'subject-preview-card '+s.color} key={s.name}><s.icon size={30}/><strong>{s.name}</strong><span>{s.text}</span><ArrowRight size={18}/></Link>)}</div></section>
    <section id="features" className="landing-feature"><div className="feature-quote"><span className="quote-spark">✦</span><p>“Không cần hiểu hết<br/>ngay hôm nay.<br/><em>Chỉ cần hiểu thêm<br/>một chút.”</em></p><span>MỘT CHÚT MỖI NGÀY, MỘT BƯỚC TIẾN MỚI.</span></div><div className="feature-mini-grid">{[{icon:BookOpen,title:"Vở vẫn là của em",text:"Giữ bản gốc, sửa chữ AI đọc nhầm, xuất bài ra Markdown."},{icon:MessageCircle,title:"Gia sư có nguồn học",text:"Xem những bài trong thư viện được dùng làm ngữ cảnh trả lời."},{icon:Gamepad2,title:"Ôn bằng nhiều cách",text:"Flashcard, quiz có giải thích và trò ghép khái niệm."},{icon:Sparkles,title:"Một không gian dễ chịu",text:"Giao diện sáng/tối, chuyển động 3D có thể tắt, dùng tốt trên điện thoại."}].map(f=><article key={f.title}><f.icon size={23}/><h3>{f.title}</h3><p>{f.text}</p></article>)}</div></section>
    <section className="landing-cta"><div className="cta-orbit"/><span className="eyebrow">ĐIỀU THÚ VỊ TIẾP THEO ĐANG CHỜ EM</span><h2>Hôm nay, em muốn<br/><em>khám phá điều gì?</em></h2><Link className="button primary" href="/register">Bắt đầu hành trình <ArrowRight size={18}/></Link><p><Check size={14}/>Em kiểm tra nội dung AI trước khi sử dụng.</p></section>
  </main><footer className="landing-footer"><Logo/><span>Một chút tò mò. Một vũ trụ kiến thức.</span><div><Link href="/privacy">Quyền riêng tư</Link><Link href="/login">Đăng nhập</Link></div></footer>
</div>;}
