"use client";
import {AppearanceControls} from "./appearance";
import {useState} from "react";import Link from "next/link";import {useRouter} from "next/navigation";
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,signInWithPopup,GoogleAuthProvider,sendEmailVerification,sendPasswordResetEmail,updateProfile} from "firebase/auth";
import {ArrowRight,ArrowLeft,Eye,EyeOff,Sparkles,Loader2} from "lucide-react";import {firebaseAuth,firebaseConfigured,authError} from "@/lib/firebase";import {Logo} from "./ui";
export function AuthForm({mode}:{mode:"login"|"register"|"reset"}){
const router=useRouter();const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [show,setShow]=useState(false);const [consent,setConsent]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");
async function submit(e:React.FormEvent){e.preventDefault();setError("");setSuccess("");
if(mode==="register"&&(password!==confirm||!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}/.test(password))){setError("Mật khẩu cần khớp và có ít nhất 8 ký tự, chữ hoa, chữ thường, số.");return;}setBusy(true);
try{const auth=firebaseAuth();if(mode==="reset"){await sendPasswordResetEmail(auth,email.trim());setSuccess("Nếu email đã đăng ký, bạn sẽ nhận được hướng dẫn đặt lại. Hãy kiểm tra cả thư rác.");}
else if(mode==="login"){await signInWithEmailAndPassword(auth,email.trim(),password);router.push("/app");}
else{const {user}=await createUserWithEmailAndPassword(auth,email.trim(),password);await updateProfile(user,{displayName:name.trim()});try{await sendEmailVerification(user);}catch{}router.push("/app");}
}catch(e){setError(authError(e));}finally{setBusy(false);}}
async function google(){setBusy(true);setError("");try{const p=new GoogleAuthProvider();p.setCustomParameters({prompt:"select_account"});await signInWithPopup(firebaseAuth(),p);router.push("/app");}catch(e){setError(authError(e));}finally{setBusy(false);}}
return <div className="auth-page"><aside className="auth-story"><Logo/><div><span className="pill"><Sparkles size={14}/> KHÔNG GIAN HỌC TẬP · LỚP 6—9</span><h2>Để mỗi điều bạn học<br/>đều trở nên<br/><em>đáng nhớ.</em></h2><p>Từ trang vở viết tay đến thư viện kiến thức.<br/>Cùng NoteLab, học theo cách của riêng bạn.</p><blockquote>Học để mỗi ngày hiểu thêm một chút.</blockquote></div><small>CHỤP · SẮP XẾP · KHÁM PHÁ · GHI NHỚ</small></aside>
<main className="auth-main"><div className="auth-appearance"><AppearanceControls/></div><Link className="back-link" href="/"><ArrowLeft size={16}/> Trang chủ</Link><div className="auth-form"><span className="eyebrow">{mode==="register"?"MỘT KHỞI ĐẦU MỚI":"CHÀO MỪNG BẠN"}</span><h1>{mode==="register"?"Tạo tài khoản của bạn":mode==="reset"?"Quên mật khẩu?":"Tiếp tục hành trình học"}</h1><p>Một vũ trụ nhỏ cho hành trình học tập THCS.</p>
{!firebaseConfigured&&<div className="notice"><strong>Dịch vụ tài khoản chưa được kết nối.</strong><span>Khám phá giao diện và trò chơi trong <Link href="/app?mode=demo">bản mẫu</Link>.</span></div>}
{mode==="register"&&<label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Tôi đã đọc <Link href="/privacy">quyền riêng tư</Link> và đồng ý ảnh/nội dung được xử lý qua Gemini và Mistral khi sử dụng AI.</span></label>}
{mode!=="reset"&&<><button className="button secondary full" disabled={busy||!firebaseConfigured||(mode==="register"&&!consent)} onClick={google}><b className="google-g">G</b> Tiếp tục với Google</button><div className="divider">hoặc dùng email</div></>}
<form onSubmit={submit}>{mode==="register"&&<label>Họ và tên<input required autoComplete="name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Bạn muốn chúng mình gọi là…"/></label>}
<label>Email<input type="email" required autoComplete="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@gmail.com"/></label>
{mode!=="reset"&&<><label>Mật khẩu<div className="password-field"><input required type={show?"text":"password"} minLength={mode==="register"?8:1} maxLength={128} autoComplete={mode==="register"?"new-password":"current-password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Nhập mật khẩu"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Ẩn mật khẩu":"Hiện mật khẩu"}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>
{mode==="register"?<><small className="hint">Ít nhất 8 ký tự, có chữ hoa, chữ thường và số.</small><label>Xác nhận mật khẩu<input required type={show?"text":"password"} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>:<Link className="forgot-link" href="/forgot-password">Quên mật khẩu?</Link>}</>}
{error&&<p className="form-error" role="alert">{error}</p>}{success&&<p className="notice" role="status">{success}</p>}
<button className="button primary full" disabled={busy||!firebaseConfigured||(mode==="register"&&!consent)}>{busy?<Loader2 className="spin" size={17}/>:null}{mode==="register"?"Tạo tài khoản":mode==="reset"?"Gửi liên kết đặt lại":"Đăng nhập"}<ArrowRight size={17}/></button></form>
<p className="auth-switch">{mode==="register"?<>Đã có tài khoản? <Link href="/login">Đăng nhập</Link></>:mode==="reset"?<Link href="/login">Quay lại đăng nhập</Link>:<>Chưa có tài khoản? <Link href="/register">Đăng ký ngay</Link></>}</p></div><small className="auth-security">Xác thực bằng Firebase Authentication.</small></main></div>;
}
