"use client";
import {useEffect,useRef,useState} from "react";import {Sparkles,MessageCircle,Send,Loader2,BookOpen,Plus} from "lucide-react";import type {Note} from "@/lib/schemas";import {api} from "@/lib/client-api";import {Title,Tag,Markdown} from "./ui";
type Message={role:"user"|"assistant";content:string};
export function ChatView({demo,note,notes,onSelect}:{demo:boolean;note:Note|null;notes:Note[];onSelect:(id:string)=>void}){
const [messages,setMessages]=useState<Message[]>([]);const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");const version=useRef(0);const end=useRef<HTMLDivElement>(null);
useEffect(()=>{const v=++version.current;setMessages([]);setError("");setBusy(false);if(demo){setLoading(false);return;}setLoading(true);api<{messages:Message[]}>("/chat"+(note?"?noteId="+note.id:"")).then(r=>{if(v===version.current)setMessages(r.messages);}).catch(e=>{if(v===version.current)setError(e.message);}).finally(()=>{if(v===version.current)setLoading(false);});},[demo,note?.id]);
useEffect(()=>{end.current?.scrollIntoView({behavior:"smooth",block:"nearest"});},[messages,busy]);
async function send(e?:React.FormEvent,question?:string){e?.preventDefault();const text=(question||input).trim();if(!text||busy||loading)return;if(demo){setError("Chatbot thật cần Gemini và tài khoản đã xác minh. Bạn đang xem giao diện mẫu; chưa có câu hỏi nào được gửi.");return;}const v=version.current;setBusy(true);setError("");try{const r=await api<{messages:Message[]}>("/chat",{method:"POST",body:JSON.stringify({message:text,noteId:note?.id})});if(v===version.current){setMessages(r.messages);setInput("");}}catch(e){if(v===version.current)setError(e instanceof Error?e.message:"Chưa gửi được câu hỏi.");}finally{if(v===version.current)setBusy(false);}}
return <><Title eyebrow="TÒ MÒ LÀ KHỞI ĐẦU CỦA HIỂU BIẾT" title="Cùng AI gỡ rối bài học" description="Hỏi điều bạn chưa hiểu. Khám phá theo nhịp riêng."/><div className="chat-layout"><div className="panel chat-panel"><div className="chat-header"><span className="ai-avatar"><Sparkles size={22}/></span><div><strong>NoteLab Tutor</strong><span>Gia sư học tập · {demo?"giao diện mẫu":"Gemini"}</span></div><Tag color="green">{note?"THEO BÀI HỌC":"HỌC TẬP CHUNG"}</Tag></div>
<div className="chat-messages" aria-live="polite">{!messages.length&&<div className="chat-welcome"><span className="big-spark"><MessageCircle size={30}/></span><h2>Hôm nay, bạn muốn hiểu thêm điều gì?</h2><p>{note?<>Cùng khám phá <strong>{note.title}</strong>, giải thích công thức hoặc thử một ví dụ.</>:"Chọn bài bên cạnh hoặc đặt câu hỏi học tập để bắt đầu."}</p><div className="chat-prompts">{["Giải thích ý chính bằng ngôn ngữ dễ hiểu","Cho mình một ví dụ và hướng dẫn từng bước","Đặt 3 câu hỏi kiểm tra mình đã hiểu bài"].map(q=><button disabled={busy||loading} key={q} onClick={()=>send(undefined,q)}><Sparkles size={14}/>{q}<Plus size={14}/></button>)}</div></div>}
{messages.map((m,i)=><div className={"message "+m.role} key={i}>{m.role==="assistant"&&<span className="message-avatar"><Sparkles size={16}/></span>}<div>{m.role==="assistant"?<Markdown content={m.content}/>:<p>{m.content}</p>}</div></div>)}{(busy||loading)&&<div className="chat-thinking"><Loader2 className="spin" size={17}/>{busy?"AI đang suy nghĩ…":"Đang tải hội thoại…"}</div>}<div ref={end}/></div>
{error&&<p className="form-error chat-error" role="alert">{error}</p>}<form className="chat-input" onSubmit={send}><label className="sr-only" htmlFor="chat-message">Câu hỏi học tập</label><textarea id="chat-message" rows={2} value={input} maxLength={3000} disabled={busy||loading} placeholder="Hỏi điều bạn đang thắc mắc…" onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><button className="send-button" disabled={busy||loading||!input.trim()} aria-label="Gửi câu hỏi"><Send size={19}/></button></form><div className="chat-disclaimer">AI có thể nhầm. Đối chiếu công thức và kết quả với tài liệu học.</div></div>
<aside className="panel chat-context"><span className="eyebrow">GÓC HỌC CỦA BẠN</span><h3><BookOpen size={19}/>Chọn nguồn kiến thức</h3><label>Bài học<select disabled={busy} value={note?.id||""} onChange={e=>onSelect(e.target.value)}><option value="">Trò chuyện học tập chung</option>{notes.map(n=><option key={n.id} value={n.id}>{n.title}</option>)}</select></label>{note&&<div className="context-note"><Tag>{note.subject}</Tag><h4>{note.title}</h4><span>{note.chapter}</span><p>{note.summary}</p></div>}<p className="context-tip"><Sparkles size={19}/>Thử hỏi: “Vì sao?”, “Khi nào dùng công thức này?” hoặc “Cho mình ví dụ khác.”</p></aside></div></>;
}
