"use client";
import {useEffect,useState} from "react";import {Layers,Zap,Puzzle,Sparkles,ArrowRight,ChevronLeft,Loader2,RotateCcw,Check,Trophy} from "lucide-react";import type {Note,StudySet,Attempt,attemptSchema} from "@/lib/schemas";import type {z} from "zod";import type {Learning} from "@/lib/use-learning";import {Title,Tag,Empty,formatDate} from "./ui";
type Mode="quiz"|"flashcards"|"match";
export function GamesView({note,notes,learning,onSelect}:{note:Note|null;notes:Note[];learning:Learning;onSelect:(id:string)=>void}){
const [study,setStudy]=useState<StudySet|null>(note?.study||null);const [mode,setMode]=useState<Mode|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [session,setSession]=useState(0);
useEffect(()=>{setStudy(note?.study||null);setMode(null);setError("");},[note?.id,note?.study]);
async function generate(){if(!note)return;setBusy(true);setError("");try{setStudy(await learning.study(note));}catch(e){setError(e instanceof Error?e.message:"Không tạo được bộ ôn.");}finally{setBusy(false);}}
const modes=[{id:"flashcards" as Mode,icon:Layers,name:"Lật thẻ, nhớ lâu",label:"FLASHCARD",text:"Một câu hỏi. Một lần nhớ lại. Lật để kiểm tra điều bạn đã hiểu.",color:"purple"},{id:"quiz" as Mode,icon:Zap,name:"Thử thách kiến thức",label:"QUIZ",text:"Chọn đáp án, xem giải thích và tìm ra phần cần học thêm.",color:"orange"},{id:"match" as Mode,icon:Puzzle,name:"Kết nối ý tưởng",label:"GHÉP ĐÔI",text:"Ghép khái niệm với ý nghĩa. Để các mảnh kiến thức kết nối.",color:"green"}];
return <><Title eyebrow="CHƠI MỘT CHÚT, NHỚ THÊM MỘT CHÚT" title="Sân chơi kiến thức" description="Bộ ôn được tạo từ một bài học đã lưu."/><div className="panel game-note-select"><label>Bạn muốn ôn bài nào?<select value={note?.id||""} disabled={busy} onChange={e=>onSelect(e.target.value)}><option value="">Chọn một bài học</option>{notes.map(n=><option key={n.id} value={n.id}>{n.subject} · {n.title}</option>)}</select></label>{note&&<Tag>{note.subject}</Tag>}</div>
{!note?<Empty title="Chọn kiến thức để bắt đầu" text="Chọn một bài học ở trên hoặc mở bài trong thư viện."/>:!study?<div className="panel generate-study"><span className="big-spark"><Sparkles size={34}/></span><h2>Từ “{note.title}” đến một cách học mới.</h2><p>AI tạo flashcard, câu hỏi trắc nghiệm và cặp khái niệm từ chính bài của bạn.</p><button className="button primary" disabled={busy} onClick={generate}>{busy?<Loader2 className="spin" size={18}/>:<Sparkles size={18}/>} {busy?"Đang tạo bộ ôn tập…":"Tạo bộ ôn tập"}</button><small>Hãy kiểm tra câu hỏi AI tạo. Sửa bài rồi tạo lại nếu cần.</small>{error&&<p className="form-error" role="alert">{error}</p>}</div>:mode?<><button className="text-button game-back" onClick={()=>{setMode(null);setSession(s=>s+1);}}><ChevronLeft size={16}/>Chọn trò khác</button><GameSession key={note.id+mode+session} note={note} study={study} mode={mode} record={input=>learning.record(input,study)}/></>:<><div className="game-cards">{modes.map(m=><button className={"game-card "+m.color} key={m.id} onClick={()=>setMode(m.id)}><span className="game-icon"><m.icon size={29}/></span><Tag color={m.color}>{m.label}</Tag><h2>{m.name}</h2><p>{m.text}</p><span className="game-card-footer">{m.id==="flashcards"?study.flashcards.length+" thẻ":m.id==="quiz"?study.quiz.length+" câu hỏi":study.pairs.length+" cặp"}<ArrowRight size={20}/></span></button>)}</div><p className="study-hint"><Sparkles size={17}/>Thử trả lời trước khi xem đáp án. Tự nhớ lại giúp bạn học chủ động hơn.</p></>}</>;
}
function GameSession({note,study,mode,record}:{note:Note;study:StudySet;mode:Mode;record:(input:z.infer<typeof attemptSchema>)=>Promise<Attempt>}){
const [index,setIndex]=useState(0);const [flipped,setFlipped]=useState(false);const [answers,setAnswers]=useState<number[]>([]);const [ratings,setRatings]=useState<("again"|"good"|"easy")[]>([]);const [choice,setChoice]=useState<number|null>(null);const [term,setTerm]=useState<number|null>(null);const [matches,setMatches]=useState<Record<number,number>>({});const [result,setResult]=useState<Attempt|null>(null);const [pending,setPending]=useState<z.infer<typeof attemptSchema>|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
const [order]=useState(()=>{const a=study.pairs.map((_,i)=>i);for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;});
const total=mode==="quiz"?study.quiz.length:mode==="flashcards"?study.flashcards.length:study.pairs.length;
async function finish(input:z.infer<typeof attemptSchema>){setPending(input);setBusy(true);setError("");try{setResult(await record(input));}catch(e){setError(e instanceof Error?e.message:"Chưa lưu được kết quả.");}finally{setBusy(false);}}
function rate(r:"again"|"good"|"easy"){const next=[...ratings,r];setRatings(next);if(index+1===total)finish({noteId:note.id,mode:"flashcards",ratings:next});else{setIndex(i=>i+1);setFlipped(false);}}
function quizNext(){if(choice===null)return;const next=[...answers,choice];setAnswers(next);if(index+1===total)finish({noteId:note.id,mode:"quiz",answers:next});else{setIndex(i=>i+1);setChoice(null);}}
function match(i:number){if(term===null)return;const next={...matches,[term]:i};setMatches(next);setTerm(null);if(Object.keys(next).length===total)finish({noteId:note.id,mode:"match",matches:study.pairs.map((_,j)=>next[j])});}
if(result)return <div className="panel game-result"><span className="trophy"><Trophy size={45}/></span><Tag color="green">MỘT BƯỚC TIẾN MỚI</Tag><h2>{result.score/result.total>=.8?"Bạn đang nắm bài rất tốt!":"Mỗi lần thử, bạn hiểu thêm."}</h2><strong className="result-score">{result.score}<span> / {result.total}</span></strong><p>{mode==="flashcards"?"thẻ bạn tự đánh giá đã nhớ":"câu trả lời đúng"}</p><div className="review-schedule"><Check size={18}/>Gợi ý ôn tiếp vào <strong>{formatDate(result.nextReviewAt)}</strong></div>{mode==="match"&&<div className="match-explanations">{study.pairs.map((p,i)=><p key={i}><span className={matches[i]===i?"correct-text":"incorrect-text"}>{matches[i]===i?"✓":"×"}</span> <strong>{p.term}</strong> → {p.definition}</p>)}</div>}<button className="button secondary" onClick={()=>{setResult(null);setPending(null);setIndex(0);setAnswers([]);setRatings([]);setFlipped(false);setChoice(null);setMatches({});}}><RotateCcw size={17}/>Ôn lại một lần</button></div>;
return <div className="panel game-session"><div className="game-session-head"><div><Tag>{mode==="quiz"?"THỬ THÁCH KIẾN THỨC":mode==="flashcards"?"FLASHCARD":"KẾT NỐI Ý TƯỞNG"}</Tag><h3>{note.title}</h3></div><span>{mode==="match"?Object.keys(matches).length:index+1} / {total}</span></div><div className="progress-track"><span style={{width:(mode==="match"?Object.keys(matches).length:index)/total*100+"%"}}/></div>
{pending?<div className="save-result"><Loader2 className={busy?"spin":""} size={26}/><h3>{busy?"Đang lưu kết quả…":"Bạn đã hoàn thành lượt ôn."}</h3>{error&&<><p className="form-error" role="alert">{error}</p><button className="button primary" onClick={()=>finish(pending)}>Thử lưu lại</button></>}</div>:mode==="flashcards"?<><button className={"flashcard "+(flipped?"flipped":"")} aria-label={flipped?"Xem câu hỏi":"Lật thẻ xem đáp án"} onClick={()=>setFlipped(!flipped)}><span>{flipped?"ĐÁP ÁN":"THỬ NHỚ LẠI"}</span><h2>{flipped?study.flashcards[index].answer:study.flashcards[index].question}</h2><small><RotateCcw size={14}/>Chạm để lật thẻ</small></button>{flipped?<div className="rating-buttons"><button className="button secondary" onClick={()=>rate("again")}>Cần học lại</button><button className="button secondary" onClick={()=>rate("good")}>Đã nhớ</button><button className="button primary" onClick={()=>rate("easy")}>Rất dễ <Check size={16}/></button></div>:<p className="center muted">Nói câu trả lời của bạn trước khi lật nhé.</p>}</>:mode==="quiz"?<><h2 className="quiz-question">{study.quiz[index].question}</h2><div className="quiz-options">{study.quiz[index].options.map((option,i)=><button className={"quiz-option "+(choice!==null&&i===study.quiz[index].answer?"correct":choice===i?"incorrect":"")} disabled={choice!==null} key={i} onClick={()=>setChoice(i)}><b>{String.fromCharCode(65+i)}</b><span>{option}</span>{choice!==null&&i===study.quiz[index].answer&&<Check size={19}/>}</button>)}</div>{choice!==null&&<div className="quiz-explanation"><strong>{choice===study.quiz[index].answer?"Chính xác!":"Cùng xem lại nhé."}</strong><p>{study.quiz[index].explanation}</p><button className="button primary" onClick={quizNext}>{index+1===total?"Xem kết quả":"Câu tiếp theo"}<ArrowRight size={17}/></button></div>}</>:<><p className="muted">Chọn khái niệm bên trái, rồi định nghĩa bên phải. Mỗi lựa chọn dùng một lần.</p><div className="match-board"><div>{study.pairs.map((p,i)=><button key={i} disabled={i in matches} className={(term===i?"selected ":"")+(i in matches?"matched":"")} onClick={()=>setTerm(i)}><b>{i+1}</b>{p.term}{i in matches&&<Check size={16}/>}</button>)}</div><div>{order.map(i=><button key={i} disabled={Object.values(matches).includes(i)||term===null} className={Object.values(matches).includes(i)?"matched":""} onClick={()=>match(i)}>{study.pairs[i].definition}</button>)}</div></div></>}</div>;
}
