"use client";
import {useRef,useState} from "react";import {Camera,UploadCloud,Sparkles,X,ChevronLeft,ChevronRight,FileText,Loader2,ShieldCheck} from "lucide-react";import {api,prepareImage} from "@/lib/client-api";import {demoNotes} from "@/lib/demo";import type {NoteInput,Extraction} from "@/lib/schemas";import {NoteEditor} from "./note-editor";import {Title,Tag} from "./ui";
const blank:NoteInput={title:"",subject:"",chapter:"",content:"",summary:"",tags:[],images:[]};
export function ScanView({demo,onSave}:{demo:boolean;onSave:(n:NoteInput)=>Promise<void>}){
const picker=useRef<HTMLInputElement>(null);const camera=useRef<HTMLInputElement>(null);const [images,setImages]=useState<NoteInput["images"]>([]);const [subject,setSubject]=useState("");const [consent,setConsent]=useState(false);const [draft,setDraft]=useState<NoteInput|null>(null);const [uncertain,setUncertain]=useState<string[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [drag,setDrag]=useState(false);
async function add(files:FileList|File[]|null){if(!files?.length)return;setError("");if(images.length+files.length>3){setError("Tối đa 3 trang vở mỗi lần.");return;}setBusy(true);try{const prepared=await Promise.all(Array.from(files).map(prepareImage));setImages(old=>[...old,...prepared].slice(0,3));}catch(e){setError(e instanceof Error?e.message:"Không xử lý được ảnh.");}finally{setBusy(false);}}
async function scan(){setBusy(true);setError("");try{const {extraction}=await api<{extraction:Extraction}>("/scan",{method:"POST",body:JSON.stringify({images,subject:subject||undefined})});setDraft({...extraction,images});setUncertain(extraction.uncertain);}catch(e){setError(e instanceof Error?e.message:"Không nhận diện được ảnh.");}finally{setBusy(false);}}
function move(i:number,d:number){setImages(old=>{const n=[...old];[n[i],n[i+d]]=[n[i+d],n[i]];return n;});}
return <><Title eyebrow="TỪ TRANG VỞ ĐẾN THƯ VIỆN" title="Ghi chép một lần. Học theo nhiều cách." description="Nhận diện chữ viết và công thức, rồi đặt kiến thức vào đúng chỗ."/><div className="scan-steps"><span className={!draft?"active":""}><b>1</b>Chọn trang vở</span><i/><span className={draft?"active":""}><b>2</b>Kiểm tra nội dung</span><i/><span><b>3</b>Lưu & khám phá</span></div>
{draft?<NoteEditor initial={draft} uncertain={uncertain} onSave={onSave} onCancel={()=>setDraft(null)}/>:<div className="scan-layout"><div className="panel scan-main"><div className={"upload-zone "+(drag?"dragging":"")} onDragOver={e=>{e.preventDefault();if(!busy)setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)add(e.dataTransfer.files);}}>
<span className="upload-icon"><UploadCloud size={35}/></span><h2>Thêm những trang vở của bạn</h2><p>Kéo ảnh vào đây, hoặc chọn từ thiết bị</p><div className="upload-actions"><button className="button primary" disabled={busy} onClick={()=>picker.current?.click()}><UploadCloud size={17}/>Chọn ảnh</button><button className="button secondary" disabled={busy} onClick={()=>camera.current?.click()}><Camera size={17}/>Chụp vở</button></div><small>JPG, PNG, WebP · tối đa 3 trang · 20 MB/ảnh trước nén</small>
<input type="file" ref={picker} className="sr-only" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>{add(e.target.files);e.target.value="";}}/><input type="file" ref={camera} className="sr-only" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>{add(e.target.files);e.target.value="";}}/></div>
{images.length>0&&<div className="image-list">{images.map((img,i)=><div className="image-item" key={i}><img src={img.dataUrl} alt={"Trang vở "+(i+1)}/><div><strong>Trang {i+1}</strong><small>{img.name}</small></div><button aria-label={"Đưa trang "+(i+1)+" lên trước"} disabled={busy||i===0} onClick={()=>move(i,-1)}><ChevronLeft size={16}/></button><button aria-label={"Đưa trang "+(i+1)+" ra sau"} disabled={busy||i===images.length-1} onClick={()=>move(i,1)}><ChevronRight size={16}/></button><button aria-label={"Bỏ trang "+(i+1)} disabled={busy} onClick={()=>setImages(old=>old.filter((_,j)=>j!==i))}><X size={16}/></button></div>)}</div>}
<div className="scan-options"><label>Môn học gợi ý (không bắt buộc)<input maxLength={160} value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Để AI nhận diện, hoặc nhập môn đang học"/></label><label className="check-label"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>Tôi đồng ý gửi các ảnh đã chọn cho Gemini để nhận diện.</span></label>
{demo&&<div className="notice"><strong>Bản mẫu chưa nhận diện ảnh.</strong><span>Thử nội dung mẫu hoặc tự viết bài. Nhận diện thật cần Gemini và tài khoản đã xác minh.</span></div>}{error&&<p className="form-error" role="alert">{error}</p>}
<button className="button primary full" disabled={busy||demo||!images.length||!consent} onClick={scan}>{busy?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>} {busy?"Đang xử lý trang vở…":"Nhận diện bằng Gemini"}</button>
<div className="scan-alternatives"><button className="text-button" disabled={busy} onClick={()=>{setDraft({...blank,subject,images});setUncertain([]);}}><FileText size={16}/>Tự viết bài mới</button>{demo&&<button className="text-button" disabled={busy} onClick={()=>{const n=demoNotes[0];setImages([]);setDraft({...n,images:[]});setUncertain(["Nội dung mẫu có sẵn để thử kiểm tra/lưu. Chưa có ảnh nào được nhận diện."]);}}>Thử nội dung mẫu <ChevronRight size={15}/></button>}</div></div></div>
<aside className="scan-tips panel"><Tag color="green">MẸO NHỎ, KẾT QUẢ TỐT HƠN</Tag><h3>Một bức ảnh rõ.<br/>Một bài học trọn vẹn.</h3>{[["Đủ ánh sáng","Tránh bóng tay và ánh sáng phản chiếu."],["Chụp thẳng trang","Giữ máy song song với mặt giấy, thấy đủ bốn góc."],["Đúng thứ tự","Sắp ảnh theo thứ tự bài trước khi nhận diện."],["Đọc lại kết quả","Chữ viết khó và công thức cần bạn kiểm tra."]].map(([title,text],i)=><div className="tip" key={title}><span>0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}<p className="tip-privacy"><ShieldCheck size={21}/>Ảnh được nén trên thiết bị. Chỉ tải nội dung bạn được phép chia sẻ.</p></aside></div>}</>;
}
