"use client";
import {useEffect,useRef,useState} from "react";
import {Mic,Square,UploadCloud,AudioLines,Loader2,FileText,Trash2,ShieldCheck} from "lucide-react";
import {api} from "@/lib/client-api";
import {AUDIO_ACCEPT,AUDIO_MAX_BYTES,AUDIO_MAX_SECONDS,audioFileError} from "@/lib/audio";
import type {NoteInput} from "@/lib/schemas";
export function VoiceNote({demo,onDraft}:{demo:boolean;onDraft:(draft:NoteInput)=>void}){
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[transcript,setTranscript]=useState(""),[error,setError]=useState(""),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false),[starting,setStarting]=useState(false),[busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0),[grade,setGrade]=useState(6),[subject,setSubject]=useState("");
 const picker=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true),timer=useRef<ReturnType<typeof setInterval>|null>(null),recordStarted=useRef(0),request=useRef<AbortController|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;request.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=="inactive")recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!file){setUrl("");return;}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);
 function choose(next:File){const message=audioFileError(next);if(message){setError(message);return;}setFile(next);setTranscript("");setConsent(false);setError("");}
 function stop(){if(recorder.current?.state!=="inactive")recorder.current?.stop();if(timer.current)clearInterval(timer.current);stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);}
 async function record(){setError("");if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setError("Trình duyệt chưa hỗ trợ ghi âm. Em có thể tải file từ ứng dụng ghi âm.");return;}setStarting(true);
 try{const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
 const mime=["audio/webm;codecs=opus","audio/mp4","audio/ogg;codecs=opus"].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(media,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:64000});recorder.current=rec;const chunks:Blob[]=[];let bytes=0;
 rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>AUDIO_MAX_BYTES&&rec.state!=="inactive"){stop();setError("Bản ghi vượt 4 MB. Hãy ghi một đoạn ngắn hơn.");}}};
 rec.onstop=()=>{if(timer.current)clearInterval(timer.current);media.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);const type=rec.mimeType||mime||"audio/webm";const extension=type.includes("mp4")?"m4a":type.includes("ogg")?"ogg":"webm";choose(new File(chunks,"ghi-am."+extension,{type}));};
 rec.onerror=()=>{stop();setError("Ghi âm bị gián đoạn. Hãy thử lại hoặc tải file lên.");};
 setFile(null);setTranscript("");setConsent(false);setSeconds(0);recordStarted.current=Date.now();rec.start(1000);setRecording(true);timer.current=setInterval(()=>{const elapsed=Math.floor((Date.now()-recordStarted.current)/1000);setSeconds(elapsed);if(elapsed>=AUDIO_MAX_SECONDS)stop();},500);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof DOMException&&e.name==="NotAllowedError"?"Em chưa cấp quyền micro. Hãy cho phép micro trong trình duyệt hoặc tải file lên.":"Không mở được micro. Hãy thử lại hoặc tải file lên.");}finally{if(alive.current)setStarting(false);}}
 async function transcribe(){if(!file||!consent||busy)return;setError("");if(demo){setError("Bản mẫu không gửi âm thanh. Đăng nhập tài khoản đã xác minh để nhận dạng thật.");return;}setBusy(true);request.current=new AbortController();
 try{const form=new FormData();form.append("audio",file);form.append("consent","true");const result=await api<{transcript:string}>("/transcribe",{method:"POST",body:form,signal:request.current.signal});if(alive.current)setTranscript(result.transcript);}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Chưa nhận dạng được âm thanh.");}finally{if(alive.current)setBusy(false);}}
 const locked=busy||recording||starting;
 return <div className="voice-layout"><section className="panel voice-main"><div className="voice-heading"><span className={"voice-orb "+(recording?"recording":"")}><AudioLines size={32}/></span><div><h2>Nói để ghi nhớ</h2><p>Đọc ý chính hoặc ghi lại lời giảng thành bài học của em.</p></div></div><div className="voice-capture"><strong>{recording?"Đang ghi âm…":"Bắt đầu bằng giọng nói"}</strong><p>{recording?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")} / 3:00 · Dừng khi đã nói xong` : "Ghi từng đoạn ngắn, tối đa 3 phút và 4 MB mỗi lượt."}</p><div className="upload-actions">{recording?<button className="button primary" onClick={stop}><Square size={16}/>Dừng ghi âm</button>:<button className="button primary" disabled={busy||starting} onClick={record}>{starting?<Loader2 className="spin" size={17}/>:<Mic size={17}/>} {starting?"Đang mở micro…":"Ghi âm"}</button>}<button className="button secondary" disabled={locked} onClick={()=>picker.current?.click()}><UploadCloud size={17}/>Tải âm thanh</button></div><input className="sr-only" aria-label="File âm thanh" ref={picker} type="file" accept={AUDIO_ACCEPT} disabled={locked} onChange={e=>{if(e.target.files?.[0])choose(e.target.files[0]);e.target.value="";}}/></div>
 {file&&<div className="voice-file"><div className="section-row"><div><strong>{file.name}</strong><small>{(file.size/1_000_000).toFixed(2)} MB · nghe lại trước khi nhận dạng</small></div><button className="icon-button" aria-label="Bỏ âm thanh" disabled={locked} onClick={()=>{setFile(null);setTranscript("");setConsent(false);}}><Trash2 size={17}/></button></div><audio controls src={url} preload="metadata" onLoadedMetadata={e=>{if(e.currentTarget.duration>AUDIO_MAX_SECONDS&&Number.isFinite(e.currentTarget.duration)){setError("Âm thanh dài hơn 3 phút. Hãy cắt thành các đoạn ngắn.");setFile(null);setTranscript("");}}}/></div>}
 <label className="check-label"><input type="checkbox" checked={consent} disabled={locked||!file} onChange={e=>setConsent(e.target.checked)}/><span>Tôi đồng ý gửi âm thanh cho VietScribe trên Hugging Face để chuyển thành văn bản.</span></label>
 {demo&&<div className="notice"><strong>Trải nghiệm giao diện mẫu</strong><span>Ghi âm và nghe lại trên thiết bị; bản mẫu không gọi VietScribe. Em có thể tự nhập bản chép lời bên dưới.</span></div>}
 <button className="button primary full" disabled={locked||!file||!consent} onClick={transcribe}>{busy?<Loader2 className="spin" size={17}/>:<AudioLines size={17}/>} {busy?"VietScribe đang nhận dạng…":"Chuyển giọng nói thành văn bản"}</button>{busy&&<p className="hint" role="status">Đang chờ VietScribe xử lý. Có thể mất vài phút khi máy chủ khởi động hoặc đang có người sử dụng.</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="voice-transcript"><div className="section-row"><h3>Kiểm tra bản chép lời</h3><small>{transcript.length.toLocaleString("vi-VN")} / 40.000</small></div><label htmlFor="voice-transcript">Nội dung nhận dạng — em có thể sửa lại</label><textarea id="voice-transcript" rows={8} maxLength={40000} disabled={locked} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Bản chép lời sẽ xuất hiện ở đây. Em cũng có thể tự nhập ghi chép."/><div className="form-row"><label>Lớp của bài học<select disabled={locked} value={grade} onChange={e=>setGrade(Number(e.target.value))}>{[6,7,8,9].map(g=><option key={g} value={g}>Lớp {g}</option>)}</select></label><label>Môn học<input disabled={locked} value={subject} maxLength={160} onChange={e=>setSubject(e.target.value)} placeholder="Ví dụ: Ngữ văn"/></label></div><button className="button primary full" disabled={locked||transcript.trim().length<10} onClick={()=>onDraft({grade,subject,title:"Ghi chép bằng giọng nói",chapter:"",content:transcript.trim(),summary:"",tags:["Giọng nói"],images:[]})}><FileText size={17}/>Tạo bài từ bản chép lời</button></div></section>
 <aside className="scan-tips panel"><span className="tag green">TỪ LỜI NÓI ĐẾN BÀI HỌC</span><h3>Nghe lại. Đọc lại.<br/>Hiểu thật rõ.</h3>{[["Chọn đoạn ngắn","Nói gần micro, tránh nhạc nền và nhiều người nói cùng lúc."],["Giữ ý chính","Đọc tên bài, môn học và từng ý một, có khoảng nghỉ."],["Kiểm tra kết quả","Sửa tên riêng, số liệu và công thức trước khi lưu."],["Học tiếp từ ghi chép","Lưu vào thư viện rồi hỏi gia sư hoặc tạo bộ ôn từ bài này."]].map(([title,text],i)=><div className="tip" key={title}><span>0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}<p className="tip-privacy"><ShieldCheck size={21}/>NoteLab lưu bản chép lời em xác nhận, không lưu file ghi âm vào thư viện. Chỉ ghi và chia sẻ nội dung khi có sự đồng ý của người nói.</p></aside></div>;
}
