"use client";
import {useEffect,useRef,useState} from "react";
import {Mic,Square,UploadCloud,AudioLines,Loader2,FileText,Trash2,ShieldCheck,Sparkles,ArrowRight} from "lucide-react";
import {api} from "@/lib/client-api";
import {AUDIO_ACCEPT,AUDIO_MAX_BYTES,AUDIO_MAX_SECONDS,audioFileError} from "@/lib/audio";
import type {NoteInput,Extraction} from "@/lib/schemas";
export function VoiceNote({demo,onDraft}:{demo:boolean;onDraft:(draft:NoteInput,uncertain?:string[],originalTranscript?:string)=>void}){
 const [file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[transcript,setTranscript]=useState(""),[error,setError]=useState(""),[consent,setConsent]=useState(false),[recording,setRecording]=useState(false),[starting,setStarting]=useState(false),[busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0),[grade,setGrade]=useState(6),[subject,setSubject]=useState("");
 const [stage,setStage]=useState<"recognize"|"organize"|null>(null);
 const transcriptField=useRef<HTMLTextAreaElement>(null);
 useEffect(()=>{const field=transcriptField.current;if(field){field.style.height="0px";field.style.height=Math.min(320,Math.max(152,field.scrollHeight))+"px";}},[transcript]);
 const picker=useRef<HTMLInputElement>(null),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),alive=useRef(true),timer=useRef<ReturnType<typeof setInterval>|null>(null),recordStarted=useRef(0),request=useRef<AbortController|null>(null);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;request.current?.abort();if(timer.current)clearInterval(timer.current);if(recorder.current){recorder.current.onstop=null;if(recorder.current.state!=="inactive")recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!file){setUrl("");return;}const u=URL.createObjectURL(file);setUrl(u);return()=>URL.revokeObjectURL(u);},[file]);
 function choose(next:File){const message=audioFileError(next);if(message){setError(message);return;}setFile(next);setTranscript("");setConsent(false);setError("");}
 function stop(){if(recorder.current?.state!=="inactive")recorder.current?.stop();if(timer.current)clearInterval(timer.current);stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);}
 async function record(){setError("");if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==="undefined"){setError("Trình duyệt chưa hỗ trợ ghi âm. Em có thể tải file từ ứng dụng ghi âm.");return;}setStarting(true);
 try{const media=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});if(!alive.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;
 const mime=["audio/webm;codecs=opus","audio/mp4","audio/ogg;codecs=opus"].find(t=>MediaRecorder.isTypeSupported(t));const rec=new MediaRecorder(media,{...(mime?{mimeType:mime}:{}),audioBitsPerSecond:64000});recorder.current=rec;const chunks:Blob[]=[];let bytes=0;
 rec.ondataavailable=e=>{if(e.data.size){chunks.push(e.data);bytes+=e.data.size;if(bytes>AUDIO_MAX_BYTES&&rec.state!=="inactive"){stop();setError("Bản ghi vượt 4 MB. Hãy ghi một đoạn ngắn hơn.");}}};
 rec.onstop=()=>{if(timer.current)clearInterval(timer.current);media.getTracks().forEach(t=>t.stop());if(!alive.current)return;setRecording(false);const type=rec.mimeType||mime||"audio/webm";const extension=type.includes("mp4")?"m4a":type.includes("ogg")?"ogg":"webm";choose(new File(chunks,"ghi-am."+extension,{type}));};
 rec.onerror=()=>{stop();setError("Ghi âm bị gián đoạn. Hãy thử lại hoặc tải file lên.");};
 setFile(null);setTranscript("");setConsent(false);setSeconds(0);recordStarted.current=Date.now();rec.start(1000);setRecording(true);timer.current=setInterval(()=>{const elapsed=Math.floor((Date.now()-recordStarted.current)/1000);setSeconds(elapsed);if(elapsed>=AUDIO_MAX_SECONDS)stop();},500);
 }catch(e){stream.current?.getTracks().forEach(t=>t.stop());setError(e instanceof DOMException&&e.name==="NotAllowedError"?"Em chưa cấp quyền micro. Hãy cho phép micro trong trình duyệt hoặc tải file lên.":"Không mở được micro. Hãy thử lại hoặc tải file lên.");}finally{if(alive.current)setStarting(false);}}
 async function organize(text:string,audio:File|null,signal:AbortSignal,fallback=false){
  setStage("organize");const form=new FormData();form.append("transcript",text);form.append("grade",String(grade));form.append("subject",subject);form.append("consentGemini","true");if(audio)form.append("audio",audio);
  const result=await api<{extraction:Extraction}>("/voice-draft",{method:"POST",body:form,signal});
  if(alive.current&&!signal.aborted)onDraft({...result.extraction,grade,images:[]},[...(fallback?["VietScribe chưa sẵn sàng; bản nháp này được Gemini đọc trực tiếp từ âm thanh."]:[]),...result.extraction.uncertain],text);
 }
 async function transcribe(){if(!file||!consent||busy)return;setError("");if(demo){setError("Bản mẫu không gửi âm thanh. Đăng nhập tài khoản đã xác minh để nhận dạng thật.");return;}setBusy(true);setStage("recognize");request.current=new AbortController();const signal=request.current.signal;
 try{const form=new FormData();form.append("audio",file);form.append("consent","true");let text="",fallback=false;
  try{const result=await api<{transcript:string}>("/transcribe",{method:"POST",body:form,signal});text=result.transcript;if(alive.current)setTranscript(text);}catch(e){if(signal.aborted||!alive.current)throw e;fallback=true;}
  if(alive.current&&!signal.aborted)await organize(text,file,signal,fallback);
 }catch(e){if(alive.current)setError(e instanceof Error?e.message:"Chưa tạo được bản ghi. Em vẫn có thể sửa và lưu bản chép lời thủ công.");}finally{if(alive.current){setBusy(false);setStage(null);}}}
 async function organizeEdited(){if(!consent||busy||transcript.trim().length<10||demo)return;setBusy(true);setError("");request.current=new AbortController();try{await organize(transcript,file,request.current.signal);}catch(e){if(alive.current)setError(e instanceof Error?e.message:"Chưa sắp xếp được. Bản chép lời vẫn được giữ lại.");}finally{if(alive.current){setBusy(false);setStage(null);}}}
 function manualDraft(){onDraft({grade,subject,title:"Ghi chép bằng giọng nói",chapter:"",content:transcript.trim(),summary:"",tags:["Giọng nói"],images:[]},["Bản chép lời chưa được Gemini kiểm tra. Hãy đọc lại trước khi lưu."],transcript);}
 const locked=busy||recording||starting;
 return <div className="voice-layout"><section className="panel voice-main"><div className="voice-heading"><span className={"voice-orb "+(recording?"recording":"")}><AudioLines size={32}/></span><div><h2>Nói để ghi nhớ</h2><p>Đọc ý chính hoặc ghi lại lời giảng thành bài học của em.</p></div></div><div className="voice-capture"><strong>{recording?"Đang ghi âm…":"Bắt đầu bằng giọng nói"}</strong><p>{recording?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")} / 3:00 · Dừng khi đã nói xong` : "Ghi từng đoạn ngắn, tối đa 3 phút và 4 MB mỗi lượt."}</p><div className="upload-actions">{recording?<button className="button primary" onClick={stop}><Square size={16}/>Dừng ghi âm</button>:<button className="button primary" disabled={busy||starting} onClick={record}>{starting?<Loader2 className="spin" size={17}/>:<Mic size={17}/>} {starting?"Đang mở micro…":"Ghi âm"}</button>}<button className="button secondary" disabled={locked} onClick={()=>picker.current?.click()}><UploadCloud size={17}/>Tải âm thanh</button></div><input className="sr-only" aria-label="File âm thanh" ref={picker} type="file" accept={AUDIO_ACCEPT} disabled={locked} onChange={e=>{if(e.target.files?.[0])choose(e.target.files[0]);e.target.value="";}}/></div>
 {file&&<div className="voice-file"><div className="section-row"><div><strong>{file.name}</strong><small>{(file.size/1_000_000).toFixed(2)} MB · nghe lại trước khi nhận dạng</small></div><button className="icon-button" aria-label="Bỏ âm thanh" disabled={locked} onClick={()=>{setFile(null);setTranscript("");setConsent(false);}}><Trash2 size={17}/></button></div><audio controls src={url} preload="metadata" onLoadedMetadata={e=>{if(e.currentTarget.duration>AUDIO_MAX_SECONDS&&Number.isFinite(e.currentTarget.duration)){setError("Âm thanh dài hơn 3 phút. Hãy cắt thành các đoạn ngắn.");setFile(null);setTranscript("");}}}/></div>}
 <label className="check-label"><input type="checkbox" checked={consent} disabled={locked||(!file&&!transcript.trim())} onChange={e=>setConsent(e.target.checked)}/><span>{file?"Tôi đồng ý gửi âm thanh cho VietScribe và Gemini, cùng bản chép lời cho Gemini để kiểm tra và sắp xếp bài học.":"Tôi đồng ý gửi ghi chép cho Gemini để kiểm tra và sắp xếp bài học."}</span></label>
 {demo&&<div className="notice"><strong>Trải nghiệm giao diện mẫu</strong><span>Ghi âm và nghe lại trên thiết bị; bản mẫu không gọi VietScribe hoặc Gemini. Em có thể tự nhập bản chép lời bên dưới.</span></div>}
 <button className="button primary full" disabled={locked||!file||!consent} onClick={transcribe}>{busy?<Loader2 className="spin" size={17}/>:<AudioLines size={17}/>} {busy?stage==="organize"?"Gemini đang kiểm tra & sắp xếp…":"VietScribe đang nhận dạng…":"Nhận dạng & tạo bản ghi"}</button>{busy&&<p className="hint" role="status">{stage==="organize"?"Đối chiếu âm thanh, đặt tên bài và chia nội dung thành các mục. Chưa lưu vào thư viện.":"Đang chờ nhận dạng. Nếu VietScribe chưa sẵn sàng, Gemini sẽ đọc trực tiếp âm thanh."}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 <div className="voice-transcript"><div className="section-row"><h3>Từ lời nói thành bài học</h3><span className="tag purple">GEMINI BIÊN TẬP</span></div><p className="voice-workflow-copy">AI tự đặt tiêu đề, phân loại môn/chủ đề và chia các ý thành mục dễ đọc. Em xem lại bản nháp trước khi lưu.</p><div className="transcript-composer"><div className="transcript-composer-head"><label htmlFor="voice-transcript">Nội dung nhận dạng — em có thể sửa lại</label><FileText size={16}/></div><textarea ref={transcriptField} id="voice-transcript" rows={5} maxLength={40000} disabled={locked} value={transcript} onChange={e=>setTranscript(e.target.value)} placeholder="Lời nói của em sẽ xuất hiện ở đây…
Em cũng có thể dán hoặc tự viết ghi chép."/><div className="transcript-composer-foot"><span>Bản gốc để đối chiếu</span><span>{transcript.length.toLocaleString("vi-VN")} / 40.000</span></div></div><div className="form-row"><label>Lớp của bài học<select disabled={locked} value={grade} onChange={e=>setGrade(Number(e.target.value))}>{[6,7,8,9].map(g=><option key={g} value={g}>Lớp {g}</option>)}</select></label><label>Môn học gợi ý<input disabled={locked} value={subject} maxLength={160} onChange={e=>setSubject(e.target.value)} placeholder="Để Gemini tự phân loại"/></label></div><button className="button primary full" disabled={demo||locked||!consent||transcript.trim().length<10} onClick={organizeEdited}>{stage==="organize"?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>} Gemini sắp xếp ghi chép <ArrowRight size={17}/></button><div className="voice-manual-action"><button className="text-button" disabled={locked||transcript.trim().length<10} onClick={manualDraft}><FileText size={15}/>Tạo bài từ bản chép lời</button><small>Lưu thủ công khi em muốn giữ nguyên nội dung</small></div></div></section>
 <aside className="scan-tips panel"><span className="tag green">TỪ LỜI NÓI ĐẾN BÀI HỌC</span><h3>Nghe lại. Đọc lại.<br/>Hiểu thật rõ.</h3>{[["Chọn đoạn ngắn","Nói gần micro, tránh nhạc nền và nhiều người nói cùng lúc."],["Giữ ý chính","Đọc tên bài, môn học và từng ý một, có khoảng nghỉ."],["Kiểm tra kết quả","Gemini đối chiếu và đánh dấu chỗ chưa chắc; em xác nhận tên riêng, số và công thức."],["Học tiếp từ ghi chép","Lưu vào thư viện rồi hỏi gia sư hoặc tạo bộ ôn từ bài này."]].map(([title,text],i)=><div className="tip" key={title}><span>0{i+1}</span><div><strong>{title}</strong><p>{text}</p></div></div>)}<p className="tip-privacy"><ShieldCheck size={21}/>NoteLab lưu bản chép lời em xác nhận, không lưu file ghi âm vào thư viện. Chỉ ghi và chia sẻ nội dung khi có sự đồng ý của người nói.</p></aside></div>;
}
