"use client";
import {useEffect,useRef,useState} from "react";import Link from "next/link";import {useRouter,useSearchParams} from "next/navigation";import {sendEmailVerification} from "firebase/auth";
import {LayoutDashboard,Library,Camera,MessageCircle,Gamepad2,Settings,LogOut,Search,Plus,ArrowRight,ArrowUpRight,Sparkles,BookOpen,ChevronRight,Check,Clock,Layers,Target,FileText,Trash2,Pencil,Download,Menu,X,ShieldCheck,Mail,RefreshCw,Atom,ChartNoAxesCombined,Languages,Brain} from "lucide-react";
import {AppearanceControls} from "./appearance";import {LearningScene} from "./learning-scene";
import {useAuth} from "./auth-provider";import {useLearning} from "@/lib/use-learning";import type {Note,NoteInput} from "@/lib/schemas";import {ScanView} from "./scan-view";import {GamesView} from "./games-view";import {ChatView} from "./chat-view";import {NoteEditor} from "./note-editor";import {Logo,Tag,Title,Spinner,Empty,Markdown,formatDate} from "./ui";
const nav=[{id:"home",label:"Tổng quan",icon:LayoutDashboard},{id:"library",label:"Thư viện kiến thức",icon:Library},{id:"scan",label:"Chụp & số hóa",icon:Camera},{id:"chat",label:"Gia sư Groq",icon:MessageCircle},{id:"games",label:"Sân chơi kiến thức",icon:Gamepad2}];
const looks=[{color:"purple",icon:ChartNoAxesCombined},{color:"orange",icon:Brain},{color:"green",icon:Atom},{color:"blue",icon:Languages}];
const fold=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d");
export function AppGate(){
 const params=useSearchParams();const router=useRouter();const {user,loading,refresh,logout}=useAuth();const demo=params.get("mode")==="demo";
 useEffect(()=>{if(!loading&&!user&&!demo)router.replace("/login");},[loading,user,demo,router]);
 if(loading||(!user&&!demo))return <Spinner label="Đang mở không gian học tập…"/>;
 if(!demo&&user&&!user.emailVerified)return <Verification email={user.email||""} resend={()=>sendEmailVerification(user)} refresh={refresh} logout={logout}/>;
 return <Workspace key={demo?"demo":user?.uid} demo={demo}/>;
}
function Verification({email,resend,refresh,logout}:{email:string;resend:()=>Promise<void>;refresh:()=>Promise<void>;logout:()=>Promise<void>}){
 const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [cooldown,setCooldown]=useState(false);
 useEffect(()=>{if(!cooldown)return;const t=setTimeout(()=>setCooldown(false),60000);return()=>clearTimeout(t);},[cooldown]);
 async function action(f:()=>Promise<void>,text:string){setBusy(true);try{await f();setMessage(text);}catch{setMessage("Chưa thực hiện được. Hãy thử lại sau.");}finally{setBusy(false);}}
 return <main className="verification"><Logo/><div className="panel verify-card"><span className="big-spark"><Mail size={35}/></span><Tag>XÁC MINH EMAIL</Tag><h1>Một bước nữa để bắt đầu.</h1><p>Mở email <strong>{email}</strong> và bấm liên kết xác minh từ Firebase. Kiểm tra thư rác hoặc gửi lại nếu chưa có thư.</p><button className="button primary full" disabled={busy} onClick={()=>action(refresh,"Nếu đã xác minh bạn sẽ vào ứng dụng. Nếu chưa, hãy mở liên kết trong thư rồi thử lại.")}><Check size={17}/>Tôi đã xác minh</button><button className="button secondary full" disabled={busy||cooldown} onClick={()=>action(async()=>{await resend();setCooldown(true);},"Đã gửi lại thư xác minh.")}><RefreshCw size={17}/>{cooldown?"Chờ 60 giây để gửi lại":"Gửi lại email"}</button>{message&&<p role="status" className="notice">{message}</p>}<button className="text-button" onClick={logout}>Đăng xuất</button></div></main>;
}
function Workspace({demo}:{demo:boolean}){
 const {user,logout}=useAuth();const learning=useLearning(demo,user?.uid);const params=useSearchParams();const router=useRouter();
 const [view,setView]=useState(params.get("view")||"home");const [selected,setSelected]=useState<Note|null>(null);const [editing,setEditing]=useState(false);const [search,setSearch]=useState("");const [subject,setSubject]=useState("");const [chapter,setChapter]=useState("");const [grade,setGrade]=useState(0);const [error,setError]=useState("");const [toast,setToast]=useState("");const [opening,setOpening]=useState(false);const [mobile,setMobile]=useState(false);const [deleting,setDeleting]=useState<Note|null>(null);const version=useRef(0);
 const subjects=[...new Set(learning.notes.map(n=>n.subject))].sort((a,b)=>a.localeCompare(b,"vi"));const style=(s:string)=>looks[Math.max(0,subjects.indexOf(s))%looks.length];const chapters=[...new Set(learning.notes.filter(n=>!subject||n.subject===subject).map(n=>n.chapter))].sort((a,b)=>a.localeCompare(b,"vi"));const name=demo?"bạn":user?.displayName?.split(" ").pop()||"bạn";
 const latest=new Map<string,(typeof learning.attempts)[number]>();for(const a of learning.attempts)if(!latest.has(a.noteId))latest.set(a.noteId,a);
 const due=learning.notes.filter(n=>{const a=latest.get(n.id);return !a||Date.parse(a.nextReviewAt)<=Date.now();});
 useEffect(()=>{const t=setTimeout(()=>setToast(""),4000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{setView(params.get("view")||"home");setMobile(false);},[params]);
 useEffect(()=>{const id=params.get("note");if(learning.loading||!id||selected?.id===id)return;let cancelled=false;setOpening(true);learning.get(id).then(n=>{if(!cancelled)setSelected(n);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setOpening(false);});return()=>{cancelled=true;};},[params,learning.loading,selected?.id]);
 function go(next:string,id=selected?.id||""){setView(next);setEditing(false);setError("");setMobile(false);const q=new URLSearchParams();if(demo)q.set("mode","demo");q.set("view",next);if(id&&["detail","chat","games"].includes(next))q.set("note",id);router.push("/app?"+q,{scroll:false});}
 async function open(id:string,next="detail"){const v=++version.current;if(!id){setSelected(null);go(next,"");return;}setOpening(true);setError("");try{const n=await learning.get(id);if(v===version.current){setSelected(n);go(next,id);}}catch(e){setError(e instanceof Error?e.message:"Không mở được bài.");}finally{if(v===version.current)setOpening(false);}}
 async function save(input:NoteInput,id?:string){const n=await learning.save(input,id);setSelected(n);setToast("Đã lưu bài vào thư viện.");go("detail",n.id);}
 async function remove(){if(!deleting)return;try{await learning.remove(deleting.id);setSelected(null);setDeleting(null);setToast("Đã xóa bài và dữ liệu ôn tập liên quan.");go("library","");}catch(e){setError(e instanceof Error?e.message:"Chưa xóa được bài.");setDeleting(null);}}
 function chooseSubject(s:string){setSubject(s);setChapter("");setSearch("");go("library");}
 const filtered=learning.notes.filter(n=>(!grade||n.grade===grade)&&(!subject||n.subject===subject)&&(!chapter||n.chapter===chapter)&&fold([n.title,n.subject,n.chapter,n.summary,...n.tags].join(" ")).includes(fold(search)));
 function exportNote(){if(!selected)return;const text=["# "+selected.title,"Lớp: "+selected.grade,"Môn: "+selected.subject,"Chương: "+selected.chapter,selected.content].join("\n\n");const url=URL.createObjectURL(new Blob([text],{type:"text/markdown;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=selected.title.replace(/[^\p{L}\p{N}\s_-]/gu,"")+".md";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="app-shell"><aside className={"sidebar "+(mobile?"mobile-open":"")}><div className="sidebar-brand"><Logo/><button className="icon-button mobile-close" aria-label="Đóng menu" onClick={()=>setMobile(false)}><X size={20}/></button></div><span className="sidebar-label">KHÔNG GIAN THCS</span><nav className="side-nav">{nav.map(n=><button key={n.id} className={view===n.id||(view==="detail"&&n.id==="library")?"active":""} onClick={()=>go(n.id)}><n.icon size={19}/><span>{n.label}</span>{n.id==="scan"&&<small>AI</small>}</button>)}</nav><div className="side-subjects"><span className="sidebar-label">MÔN HỌC CỦA BẠN</span>{subjects.slice(0,6).map(s=><button key={s} onClick={()=>chooseSubject(s)}><i className={"subject-dot "+style(s).color}/><span>{s}</span><small>{learning.notes.filter(n=>n.subject===s).length}</small></button>)}</div><div className="sidebar-bottom"><div className="sidebar-note"><span>✦</span><strong>Một chút mỗi ngày.</strong><p>Kiến thức lớn lên từ những bước nhỏ.</p><button onClick={()=>go("games")}>Ôn tập hôm nay <ArrowUpRight size={15}/></button></div><button className={"settings-nav "+(view==="settings"?"active":"")} onClick={()=>go("settings")}><Settings size={19}/>Tài khoản & kết nối</button><div className="sidebar-user"><span className="user-avatar">{demo?"N":(user?.displayName||user?.email||"B").charAt(0).toUpperCase()}</span><div><strong>{demo?"Không gian mẫu":user?.displayName||"Người học"}</strong><small>{demo?"Khám phá NoteLab":user?.email}</small></div><button className="icon-button" aria-label={demo?"Về trang chủ":"Đăng xuất"} onClick={()=>{if(demo)router.push("/");else logout().then(()=>router.push("/login"));}}><LogOut size={18}/></button></div></div></aside>{mobile&&<button className="sidebar-scrim" aria-label="Đóng menu" onClick={()=>setMobile(false)}/>}
 <div className="app-main"><header className="app-header"><div className="header-left"><button className="icon-button hamburger" aria-label="Mở menu" onClick={()=>setMobile(true)}><Menu size={22}/></button><span className="breadcrumb">Không gian của em <ChevronRight size={14}/><strong>{nav.find(n=>n.id===view)?.label||(view==="detail"?"Bài học":"Tài khoản")}</strong></span></div><div className="header-right"><AppearanceControls/><div className="header-search"><Search size={16}/><input aria-label="Tìm trong thư viện" value={search} placeholder="Tìm kiến thức…" onChange={e=>{setSearch(e.target.value);if(view!=="library")go("library");}}/></div><span className="today">{new Date().toLocaleDateString("vi-VN",{day:"numeric",month:"long",timeZone:"Asia/Ho_Chi_Minh"})}</span></div></header>
 {demo&&<div className="demo-banner"><span><Sparkles size={15}/><strong>Không gian mẫu</strong> · Bài & kết quả lưu trên thiết bị. AI và dữ liệu cloud chưa được sử dụng.</span><Link href="/register">Tạo tài khoản <ArrowRight size={14}/></Link></div>}
 <main className="workspace-content">{(error||learning.error)&&<div className="error-banner" role="alert"><span>{error||learning.error}</span><button onClick={()=>{setError("");learning.load();}}><RefreshCw size={15}/>Thử lại</button></div>}{opening&&<Spinner label="Đang mở bài học…"/>}
 {learning.loading?<Spinner label="Đang tải thư viện…"/>:view==="home"?<>
 <Title eyebrow="HỌC THÊM MỘT CHÚT MỖI NGÀY" title={"Chào "+name+", cùng khám phá nhé!"} description="Một trang vở, một ý tưởng. Mỗi ngày hiểu thêm một chút."><button className="button primary" onClick={()=>go("scan")}><Plus size={17}/>Thêm bài học</button></Title>
 <section className="dashboard-hero"><div className="dashboard-hero-copy"><span className="hero-small-tag"><Sparkles size={14}/>VŨ TRỤ HỌC TẬP · LỚP 6—9</span><h2>Một chút tò mò.<br/><span>Một vũ trụ kiến thức.</span></h2><p>Chụp lại bài học. Để AI giúp bạn sắp xếp,<br/>hiểu sâu và ôn theo cách thú vị hơn.</p><button className="button white" onClick={()=>go("scan")}><Camera size={17}/>Chụp trang vở đầu tiên <ArrowRight size={17}/></button></div><LearningScene compact/></section>
 <div className="stats-grid">{[{icon:BookOpen,label:"Bài học đã tải",value:learning.notes.length,color:"purple"},{icon:Layers,label:"Môn học đang khám phá",value:subjects.length,color:"orange"},{icon:Target,label:"Lượt ôn gần đây",value:learning.attempts.length,color:"green"},{icon:Clock,label:"Bài chờ ôn / bắt đầu",value:due.length,color:"blue"}].map(s=><div className="panel stat-card" key={s.label}><span className={"stat-icon "+s.color}><s.icon size={22}/></span><div><strong>{s.value}</strong><span>{s.label}</span></div></div>)}</div>
 <section><div className="section-row"><h2>Góc kiến thức của bạn <span>{subjects.length}</span></h2><button className="text-button" onClick={()=>{setSubject("");setChapter("");go("library");}}>Xem thư viện <ArrowRight size={15}/></button></div>{subjects.length?<div className="subject-cards">{subjects.map(s=>{const st=style(s);const list=learning.notes.filter(n=>n.subject===s);return <button className={"subject-card "+st.color} key={s} onClick={()=>chooseSubject(s)}><div><st.icon size={26}/><ArrowUpRight size={17}/></div><h3>{s}</h3><p>{list.length} bài học · {new Set(list.map(n=>n.chapter)).size} chương</p><div className="subject-bar"><span/></div></button>;})}</div>:<Empty title="Một thư viện đang chờ bạn viết nên" text="Thêm trang vở đầu tiên. Môn học và chương sẽ xuất hiện ở đây."><button className="button primary" onClick={()=>go("scan")}>Thêm bài đầu tiên</button></Empty>}</section>
 <div className="dashboard-lower"><section><div className="section-row"><h2>Mở lại một trang vở</h2><button className="text-button" onClick={()=>go("library")}>Tất cả <ArrowRight size={15}/></button></div><div className="panel recent-notes">{learning.notes.slice(0,4).map(n=><button key={n.id} onClick={()=>open(n.id)}><span className={"recent-icon "+style(n.subject).color}><FileText size={22}/></span><div><strong>{n.title}</strong><span>{n.subject} · {n.chapter}</span></div><small>{formatDate(n.updatedAt)}</small><ChevronRight size={16}/></button>)}</div></section><aside className="review-card"><Gamepad2 size={29}/><Tag color="orange">HỌC BẰNG CÁCH CHƠI</Tag><h3>Nhớ lại.<br/>Kết nối. Hiểu sâu.</h3><p>Một lượt flashcard, một quiz ngắn. Kiến thức vừa học sẽ ở lại lâu hơn.</p><button onClick={()=>{const n=learning.notes.find(n=>n.study)||due[0]||learning.notes[0];if(n)open(n.id,"games");else go("scan");}}>Bắt đầu ôn tập <ArrowRight size={18}/></button></aside></div>
 </>:view==="library"?<>
 <Title eyebrow="MỌI ĐIỀU BẠN HỌC, ĐÚNG NƠI BẠN CẦN" title="Thư viện kiến thức" description={learning.notes.length+" bài đã tải · Môn học, chương và chủ đề."}><button className="button primary" onClick={()=>go("scan")}><Plus size={17}/>Thêm bài học</button></Title>
 <div className="panel library-filters"><div className="search-input"><Search size={18}/><input aria-label="Tìm bài học" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm tên bài, tóm tắt, thẻ chủ đề…"/></div><label className="sr-only" htmlFor="grade-filter">Lọc lớp học</label><select id="grade-filter" value={grade} onChange={e=>{setGrade(Number(e.target.value));setSubject("");setChapter("");}}><option value={0}>Tất cả lớp</option>{[6,7,8,9].map(g=><option value={g} key={g}>Lớp {g}</option>)}</select><label className="sr-only" htmlFor="subject-filter">Lọc môn học</label><select id="subject-filter" value={subject} onChange={e=>{setSubject(e.target.value);setChapter("");}}><option value="">Tất cả môn học</option>{subjects.map(s=><option key={s}>{s}</option>)}</select><label className="sr-only" htmlFor="chapter-filter">Lọc chương</label><select id="chapter-filter" value={chapter} onChange={e=>setChapter(e.target.value)}><option value="">Tất cả chương</option>{chapters.map(c=><option key={c}>{c}</option>)}</select></div>
 {filtered.length?<div className="library-groups">{[...new Set(filtered.map(n=>JSON.stringify([n.grade,n.subject,n.chapter])))].map(key=>{const [g,s,ch]=JSON.parse(key) as [number,string,string];const group=filtered.filter(n=>n.grade===g&&n.subject===s&&n.chapter===ch);return <section key={key}><div className="library-group-head"><i className={"subject-dot "+style(s).color}/><span className="grade-label">Lớp {g}</span><h2>{s}</h2><ChevronRight size={14}/><span>{ch}</span><small>{group.length} bài</small></div><div className="note-grid">{group.map(n=><button className="panel note-card" key={n.id} onClick={()=>open(n.id)}><div className="note-card-top"><span className={"recent-icon "+style(s).color}><FileText size={20}/></span><small>{formatDate(n.updatedAt)}</small></div><h3>{n.title}</h3><p>{n.summary||"Mở bài để khám phá nội dung."}</p><div className="note-tags">{n.tags.slice(0,3).map(t=><Tag key={t} color={style(s).color}>{t}</Tag>)}</div><div className="note-card-footer">Khám phá bài học <ArrowUpRight size={17}/></div></button>)}</div></section>;})}</div>:<Empty title={learning.notes.length?"Chưa tìm thấy bài phù hợp":"Thư viện bắt đầu từ đây"} text="Thử từ khóa khác hoặc thêm một trang vở."><button className="button secondary" onClick={()=>{setSearch("");setSubject("");setChapter("");setGrade(0);if(!learning.notes.length)go("scan");}}>{learning.notes.length?"Đặt lại bộ lọc":"Thêm bài học"}</button></Empty>}{learning.hasMore&&<button className="button secondary full" onClick={()=>learning.more().catch(e=>setError(e.message))}>Tải thêm bài học</button>}
 </>:view==="scan"?<ScanView demo={demo} onSave={n=>save(n)}/>:view==="chat"?<ChatView demo={demo} note={selected} notes={learning.notes} onSelect={id=>open(id,"chat")} onOpenSource={id=>open(id,"detail")}/>:view==="games"?<GamesView note={selected} notes={learning.notes} learning={learning} onSelect={id=>open(id,"games")}/>:view==="detail"?selected?editing?<NoteEditor key={selected.id} initial={selected} editing onSave={n=>save(n,selected.id)} onCancel={()=>setEditing(false)}/>:<>
 <div className="detail-breadcrumb"><button onClick={()=>go("library")}>Thư viện</button><ChevronRight size={15}/><span>Lớp {selected.grade} · {selected.subject}</span><ChevronRight size={15}/><span>{selected.chapter}</span></div><div className="note-detail-header"><div><Tag color={style(selected.subject).color}>{selected.subject}</Tag><h1>{selected.title}</h1><p>Cập nhật {formatDate(selected.updatedAt)} · {selected.content.split(/\s+/).filter(Boolean).length} từ</p></div><div className="detail-actions"><button className="icon-button" aria-label="Tải bài học dạng Markdown" onClick={exportNote}><Download size={19}/></button><button className="icon-button" aria-label="Chỉnh sửa bài học" onClick={()=>setEditing(true)}><Pencil size={19}/></button><button className="icon-button danger" aria-label="Xóa bài học" onClick={()=>setDeleting(selected)}><Trash2 size={19}/></button></div></div>
 <div className="detail-layout"><article className="panel note-document">{selected.summary&&<div className="note-summary"><span><Sparkles size={16}/>Ý CHÍNH TRONG MỘT PHÚT</span><p>{selected.summary}</p></div>}<Markdown content={selected.content}/>{selected.images.length>0&&<details className="source-images"><summary>Ảnh trang vở đã lưu ({selected.images.length})</summary>{selected.images.map((img,i)=><img key={i} src={img.dataUrl} alt={"Trang vở "+(i+1)}/>)}</details>}</article><aside className="detail-side"><div className="panel"><span className="eyebrow">ĐI TIẾP TỪ ĐÂY</span><h3>Hiểu bài theo cách của bạn</h3><button className="detail-cta" onClick={()=>go("chat")}><MessageCircle size={23}/><span><strong>Hỏi gia sư AI</strong><small>Giải thích, ví dụ và câu hỏi</small></span><ChevronRight size={17}/></button><button className="detail-cta" onClick={()=>go("games")}><Gamepad2 size={23}/><span><strong>Tạo một lượt ôn tập</strong><small>Flashcard · Quiz · Ghép đôi</small></span><ChevronRight size={17}/></button></div><div className="panel"><h4>Thẻ chủ đề</h4><div className="note-tags">{selected.tags.map(t=><Tag key={t}>{t}</Tag>)}</div></div><div className="panel detail-notice"><ShieldCheck size={20}/><p>Kiểm tra chữ, công thức và kiến thức AI tạo trước khi ôn tập.</p></div></aside></div>
 </>:<Empty title="Chọn một bài để khám phá" text="Mở thư viện để tiếp tục."><button className="button primary" onClick={()=>go("library")}>Mở thư viện</button></Empty>:<SettingsView demo={demo} name={user?.displayName||"Người học"} email={user?.email||""} reset={()=>{learning.reset();setSelected(null);setToast("Đã đặt lại dữ liệu mẫu.");}}/>}
 </main><footer className="workspace-footer"><span>notelab. <i>Học theo cách của bạn.</i></span><Link href="/privacy">Quyền riêng tư</Link></footer></div>{toast&&<div className="toast" role="status"><Check size={18}/>{toast}</div>}{deleting&&<DeleteDialog note={deleting} cancel={()=>setDeleting(null)} remove={remove}/>}</div>;
}
function DeleteDialog({note,cancel,remove}:{note:Note;cancel:()=>void;remove:()=>Promise<void>}){
 const ref=useRef<HTMLDialogElement>(null);const [busy,setBusy]=useState(false);useEffect(()=>{ref.current?.showModal();},[]);
 return <dialog className="confirm-dialog" ref={ref} onCancel={e=>{e.preventDefault();if(!busy)cancel();}}><span className="delete-icon"><Trash2 size={27}/></span><h2>Xóa bài học này?</h2><p><strong>{note.title}</strong>, ảnh, bộ ôn, kết quả và hội thoại theo bài sẽ bị xóa. Không thể hoàn tác.</p><div><button className="button secondary" disabled={busy} onClick={cancel}>Giữ lại bài</button><button className="button danger-button" disabled={busy} onClick={async()=>{setBusy(true);await remove();setBusy(false);}}>{busy?"Đang xóa…":"Xóa bài học"}</button></div></dialog>;
}
function SettingsView({demo,name,email,reset}:{demo:boolean;name:string;email:string;reset:()=>void}){
 const [status,setStatus]=useState<{firebase:boolean;gemini:boolean;groq:boolean;turso:boolean}|null>(null);const [error,setError]=useState("");
 async function check(){setError("");try{const r=await fetch("/api/status",{cache:"no-store"});if(!r.ok)throw new Error();setStatus(await r.json());}catch{setError("Chưa kiểm tra được cấu hình.");}}
 useEffect(()=>{check();},[]);
 return <><Title eyebrow="KHÔNG GIAN CỦA RIÊNG BẠN" title="Tài khoản & kết nối" description="Thông tin tài khoản và cấu hình các dịch vụ."/><div className="settings-grid"><section className="panel settings-card"><span className="user-avatar large">{demo?"N":name.charAt(0)}</span><h2>{demo?"Không gian mẫu":name}</h2><p>{demo?"Dữ liệu lưu trong trình duyệt này.":email}</p><Tag color="green">{demo?"TRẢI NGHIỆM TRÊN THIẾT BỊ":"EMAIL ĐÃ XÁC MINH"}</Tag>{demo&&<><Link className="button primary full" href="/register">Tạo tài khoản thật <ArrowRight size={16}/></Link><button className="button secondary full" onClick={()=>{if(window.confirm("Đặt lại bài học và kết quả trong bản mẫu trên thiết bị này?")){try{reset();}catch(e){setError(e instanceof Error?e.message:"Không đặt lại được.");}}}}>Đặt lại dữ liệu mẫu</button></>}</section><section className="panel settings-card"><div className="section-row"><h2>Các dịch vụ học tập</h2><button className="icon-button" aria-label="Kiểm tra lại trạng thái" onClick={check}><RefreshCw size={17}/></button></div><p className="muted">Chỉ kiểm tra đã cung cấp cấu hình; chưa xác nhận kết nối trực tiếp.</p>{[{key:"firebase" as const,name:"Firebase Authentication",text:"Đăng nhập và xác minh email",icon:ShieldCheck},{key:"gemini" as const,name:"Google Gemini",text:"Nhận diện vở và tạo bộ ôn",icon:Sparkles},{key:"groq" as const,name:"Groq AI",text:"Gia sư dựa trên thư viện của em",icon:MessageCircle},{key:"turso" as const,name:"Turso Database",text:"Bài học và tiến độ cá nhân",icon:Library}].map(s=><div className="service-status" key={s.key}><s.icon size={23}/><div><strong>{s.name}</strong><span>{s.text}</span></div><Tag color={status?.[s.key]?"green":"orange"}>{status?status[s.key]?"ĐÃ CẤU HÌNH":"CHƯA CẤU HÌNH":"ĐANG KIỂM TRA"}</Tag></div>)}{error&&<p className="form-error" role="alert">{error}</p>}<div className="notice"><strong>Dành cho quản trị viên</strong><span>Hướng dẫn Firebase, Gemini, Turso và Vercel nằm trong repository.</span><a href="https://github.com/hungle2006/Note_App/blob/main/docs/DEPLOYMENT.md" target="_blank" rel="noreferrer">Mở hướng dẫn cấu hình ↗</a></div></section></div><section className="panel data-principles"><ShieldCheck size={25}/><div><h3>Học tập với quyền riêng tư rõ ràng</h3><p>Ảnh chỉ gửi cho Gemini khi bạn chọn nhận diện. Mỗi tài khoản có thư viện riêng. Tải bài thành Markdown hoặc xóa từng bài khi cần.</p><Link href="/privacy">Đọc chính sách quyền riêng tư →</Link></div></section></>;
}
